import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Issue4.module.css'

export default function Issue4() {
  return (
    <div>
      <Head>
        <title>new_sinews issue4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

        <div className={styles.pageStructure}>
          <div className={styles.issueContents}>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... brandon shimoda + the hour of the rat ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... k-ming chang + guanyin ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... evan isoline + as foam from this sweet hour ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... christa romanosky + how far you can get on an empty tank of gas ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... gabriel palacios + poems from lunar hilton elegy ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... allison hummel + the fires are back // i look at sauce // untitled // comfort like the ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... mike corrao + text spinality ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... vi khi nao + poems born from basic words ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">... grant maierhofer + in the time when my memory fixated on the
          death of princess diana ...</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">~~~ contri butor_ _ _b  i  os ~~~</a>
          </div>
          </div>

             <div className={styles.issueDecor}>
             <div className={styles.titleAndSubtitle}>
               _ n e w + <br/>s i n e w s _<br/><br/><span className={styles.subtitle}>issue _ 4</span></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.backgroundBox}></div>
             <div className={styles.siteShortcuts}>
                   <button className={styles.linkButton}><a
                   className={styles.innerSiteLinkTag} href="https://newnewsinews.com">new sinews</a></button>
                   <button className={styles.linkButton}><a
                   className={styles.innerSiteLinkTag} href="https://newnewsinews.com/about">about</a></button>
                   <button className={styles.linkButton}>
                     <a className={styles.twitterLinkTag} href="https://twitter.com/new_sinews">[Bird App]</a>
                   </button>
                   </div>
             </div>
        </div>

        </div>
      )
    }
