import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightGrayTitle from '../../components/rightGrayTitle.js'
import CenterBlackTitle from '../../components/centerBlackTitle.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Isoline.module.css'

export default function Isoline() {
  return (
      <div>
          <Head>
            <title>evan_isoline ~ as_foam_from_this_sweet_hour — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="isolineBackground"/>

       <RightGrayTitle><h3 className={styles.title}>><span className={styles.titleShadow}><span
       className={styles.inverseShadow}>a</span>s<br/>foam<span
       className={styles.inverseShadow}><br/>f</span>r<span
       className={styles.inverseShadow}>o</span>m t<span
       className={styles.inverseShadow}>h</span>i<span
       className={styles.inverseShadow}>s</span><br/><span
       className={styles.inverseShadow}>sweet</span><br/>h<span
       className={styles.inverseShadow}>o</span>u<span
       className={styles.inverseShadow}>r</span></span></h3></RightGrayTitle>

       <br/>

        <CenterBlackTitle><span className={styles.bareHeader}>... ...evan + isoline... ...</span>
        </CenterBlackTitle>

        <br/><br/>

<pre className={styles.foam}>{`A wildflower head with a nowness I am. The ism of absence.
Lookit here, lookee there. Where they bristle—throng together
in pink Samhain.


Loose boots, la dolce vita, the melding
smother.


Heh. I for one am baffled. It’s a cosmic
joke. A denouement.




Maybe I’m conceited, or

entitled even, when I resent your

radiant speculations that cannot stop

the brainlike thesaurus of the dollar.


This is the value, the doll’s house, the
virus and the cameraman are

lining themselves up with the dioramas

and choreographing the fate of this myth.
I’ll not shame thy lustrous raiment. Enter this way

With words as sleek as blades. Breathe
your bass over the
codeine cadence




So electric, yet, through the stems we swim in
inflexion. So who's no touch can even?

Surprise the move of heart by glass wolves on bone branches.

This is how we mix like species before
Release

No itty bitty red pill. No itty bitty blue
pill.



Waterfalls of vitamin C. The colors are calibrated for sunsets. Why is its presence a transgression?
You saw how we were beginning, you do what you do, but I could not bear to imagine your own
enema of red ants… You want to see me become ekphrasis, the jewel that blooms in indigo.


My violence has its own kind of tingle. Unrecognize the gas-orange flounce crumpling over time.
A comet that might have been. A supernova that might have been. The slow tip of the exponential
funnel with incinerated lips. The vaporising slag face of unprincipled gullibility. The ghost
anthracite.`}</pre>

                     <Footer/>
                           </body>
                       </div>
                   )
                 }
