import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/EvenFlesh.module.css'

export default function EvenFlesh() {
  return (
      <div className={styles.container}>
          <Head>
            <title>even flesh seems a formality_or: Vi Khi Nao's organic oscillations — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header/>

       <p className={styles.compositionTitle}>even flesh seems a formality</p>
       <p className={styles.proseTitle}>or: Vi Khi Nao’s organic oscillations</p>

       <p className={styles.authorItalic}>Steve Barbaro</p>

       <article className={styles.standardProse}>
       How might the partakers of cynically sensible deeds be freed in the very course of their yielding? “The virtue of ecstasy robs reality of its synthetic robes,” Vi Khi Nao answers by way of her first book, The Vanishing Point of Desire (2011). And in this novel-in-roomily-white-spaced-prose, the bleh ritual of a two-person interview in a conference room is rejigged, via the 1st person narrator’s eros-engined mid-interview reveries, to encapsulate Charles de Gaulle Airport, of all earthly backdrops.
       <br/>
       <br/>
       As if said hub of hubbub might indeed prove a kind of ideal destination, the interview-ensconced interviewer-narrator recurrently muses—so as to ground the novel in an escape-dense space—upon “the city made of arrivals and departures.” Not to be ensnared however, the narrative is thence redirected into the interviewer’s own paintings which dangle, for some reason, from the airport’s ceiling. Weirdly convincingly, and via the descriptively-consummated engine of latent interviewer-interviewee attraction, the interview’s constituents thus assume the very space of inert canvases. The proper remedy for thwarting the soul-sapping ceremonies undergirding much of “normal life” is as such a redoubled dose of fiction; and the-novel-according-to-Nao, in all of its self-propelling self-corrections, manifests as a sensorium where incompatible-seeming entities perched at not inconsiderable removes attain astonishingly urgent correspondence, up to and including “the torment or equanimity they must feel having to exist with one another.”
       </article>

    <Footer/>
          </body>
      </div>
  )
}
