import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import AuthorName from '../../components/authorName.js'
import CompositionTitle from '../../components/compositionTitle.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Gridley.module.css'

export default function Romanosky() {
  return (
      <div className={styles.container}>
          <Head>
            <title>sarah_gridley ~ four_poems — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

          <Header headerBackground="gridleyBackground"/>

          <AuthorName authorName="sarah gridley"/>
          <CompositionTitle compositionTitle="four poems"/>
          <p className={styles.poemTitle}>Do No Harm</p>
          <pre className={styles.standardLineation}>{`
      As if the bird were not
      in one room, but many, and making the sound of many seabirds
      pinning dunes to blue and vibrant yards of wind. That sanding down
      was why,
      was surely what I felt the credo
      was, no mean or desperate motion, no graceless
      tangling in the rafters, but light as fire to an open flue,
      the relic beehive feathering up
      to ashes in the draft. This was where
      I told myself to live. And pressed my life to going over
      everything I did.
            `}</pre>

            <p className={styles.poemTitle}>Chair</p>
            <pre className={styles.standardLineation}>{`
      The chair is a gesture. Of all
      the motions, there are two hands always
      pulling the chair out, or one hand saying, Sit down,
      it’s free. Now its wood shines with absence.
      Now it hardens to oak. Of all the wearing evenings
      and mornings, the chair, unlike
      a boat, is never named. Years pass and the chair goes by
      in duplicate, profligate, a map of lowered anchors
      printed so small they look like stars.
              `}</pre>

            <p className={styles.poemTitle}>Compounding Pharmacy</p>
            <pre className={styles.standardLineation}>{`
      Disquiet adopts                           a whetstone’s grit
      An undercroft                              had better be what you think it is
      A timepiece                                 cleans its feathers in the spring
      As a windfall                                is wise to attachment
      Attachment is a metaphysic       hunting from the ground
              `}
            </pre>

            <p className={styles.poemTitle}>Unsound Supposition</p>
            <pre className={styles.standardLineation}>{`
      Dampened drums
      of thunder, strong sheets of rain
      you eye through the front door window,
      numbering the obligations to a house. Unsound
      supposition, that this overflow was caused
      by leaves. Cleaning the gutters, you’d had two
      wasp-stings in one day. The unaggressive
      paper-wasps had only just derived the delicate
      umbel of their hive. Acid for wasp venom,
      alkaline for bee. How deadly sweet it is,
      a datum, so way beside the point, but pointed
      nonetheless, desirable stings of quibbling,
      quarreling, jockeying for the smallest powers.
      I read that Petty Dancers is an older
      name for Northern Lights.
      A whale had fur. A whale was once
      a proto mouse.
              `}</pre>

          <Footer/>

          </body>

          </div>

        )

      }
