import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Issue1.module.css'

export default function Issue1() {
  return (
      <>
      <Head>
        <title>new_sinews issue1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <div className={styles.fullPageBackground}>

      <body className={styles.pageStructure}>

      <div className={styles.pageTitle}>new_sinews</div>

    <div className={styles.issueContents}>
      <div className={styles.issue}>issue_1</div>
      <div className={styles.col1}>
        <div className={styles.workLink}><Link href="/issue1/gridley">sarah gridley_four poems</Link></div>
      </div>
      <div className={styles.col1}>
          <div className={styles.workLink}><Link href="/issue1/blackwell">gabriel blackwell_two stories</Link></div>
      </div>
      <div className={styles.col1}>
          <div className={styles.workLink}><Link href="/issue1/romanosky">christa romanosky_three poems</Link></div>
      </div>
      <div className={styles.col2}>
        <div className={styles.workLink}><Link href="/issue1/eisen-martin">tongo eisen-martin_two poems</Link></div>
      </div>
      <div className={styles.col2}>
        <div className={styles.workLink}><Link href="/issue1/two-eyes-in-one">vi khi nao_2 eyes in 1 eye: a delirium</Link></div>
      </div>
      <div className={styles.col2}>
        <Link href="/issue1/even-flesh"><a className={styles.workLink} href=""
        >even flesh seems a formality<br/>or: vi khi nao's organic
          oscillations
        </a></Link>
        <Link href="/issue1/bios"><a className={styles.workLink} href="">~~~b  i  os ~~~</a></Link>
      </div>

      <div className={styles.siteShortcuts}>
            <Link href="/"><button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com">new sinews</a></button></Link>
            <button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com/about">about</a></button>
            <button className={styles.linkButton}>
              <a className={styles.twitterLinkTag} href="https://twitter.com/new_sinews">[Bird App]</a>
            </button>
        </div>
    </div>
 </body>
      </div>
      </>
  )
}
