import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Romanosky.module.css'

export default function Romanosky() {
  return (
      <div className={styles.container}>
          <Head>
            <title>christa_romanosky_three_poems — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

          <Header/>

          <Footer/>

          </body>

          </div>

        )

      }
