import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/TwoEyesInOne.module.css'

export default function TwoEyesInOneEye() {
  return (
      <div className={styles.container}>
          <Head>
            <title>vi_khi_nao ~ two_eyes_in_one_eye: a_delirium — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

          <Header headerBackground="naoBackground"/>


<div class="slideshow-container">


 <div class="mySlides fade">
   <div class="numbertext">1 / 3</div>
   <img src="img1.jpg" style="width:100%"/>
   <div class="text">Caption Text</div>
 </div>

 <div class="mySlides fade">
   <div class="numbertext">2 / 3</div>
   <img src="img2.jpg" style="width:100%"/>
   <div class="text">Caption Two</div>
 </div>

 <div class="mySlides fade">
   <div class="numbertext">3 / 3</div>
   <img src="img3.jpg" style="width:100%"/>
   <div class="text">Caption Three</div>
 </div>


 <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
 <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br/>


<div style="text-align:center">
 <span class="dot" onclick="currentSlide(1)"></span>
 <span class="dot" onclick="currentSlide(2)"></span>
 <span class="dot" onclick="currentSlide(3)"></span>
</div>


          <Footer/>

          </body>

          </div>

        )

      }
