import { TombModel1RawText1 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText2 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText3 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText4 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText5 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText6 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText7 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText8 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText9 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText10 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText11 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText12 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText13 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText14 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText15 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText16 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText17 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText18 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText19 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText20 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText21 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText22 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText23 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText24 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText25 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText26 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText27 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText28 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText29 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText30 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText31 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText32 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText33 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText34 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText35 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText36 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText37 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText38 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText39 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText40 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText41 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText42 } from "../galleryText/tombModelGalleryText.js";
import { TombModel1RawText43 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText1 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText2 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText3 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText4 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText5 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText6 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText7 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText8 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText9 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText10 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText11 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText12 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText13 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText14 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText15 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText16 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText17 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText18 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText19 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText20 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText21 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText22 } from "../galleryText/tombModelGalleryText.js";
import { TombModel2RawText23 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText0 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText1 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText2 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText3 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText4 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText5 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText6 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText7 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText8 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText9 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText10 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText11 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText12 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText13 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText14 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText15 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText16 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText17 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText18 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText19 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText20 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText21 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText22 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText23 } from "../galleryText/tombModelGalleryText.js";
import { TombModel3RawText24 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText1 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText2 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText3 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText4 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText5 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText6 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText7 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText8 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText9 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText10 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText11 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText12 } from "../galleryText/tombModelGalleryText.js";
import { TombModel4RawText13 } from "../galleryText/tombModelGalleryText.js";

export const tombModelOneText = [
  { title: "TombModel1", textName: TombModel1RawText1 },
  { title: "TombModel2", textName: TombModel1RawText2 },
  { title: "TombModel3", textName: TombModel1RawText3 },
  { title: "TombModel4", textName: TombModel1RawText4 },
  { title: "TombModel5", textName: TombModel1RawText5 },
  { title: "TombModel6", textName: TombModel1RawText6 },
  { title: "TombModel7", textName: TombModel1RawText7 },
  { title: "TombModel8", textName: TombModel1RawText8 },
  { title: "TombModel9", textName: TombModel1RawText9 },
  { title: "TombModel10", textName: TombModel1RawText10 },
  { title: "TombModel11", textName: TombModel1RawText11 },
  { title: "TombModel12", textName: TombModel1RawText12 },
  { title: "TombModel13", textName: TombModel1RawText13 },
  { title: "TombModel14", textName: TombModel1RawText14 },
  { title: "TombModel15", textName: TombModel1RawText15 },
  { title: "TombModel16", textName: TombModel1RawText16 },
  { title: "TombModel17", textName: TombModel1RawText17 },
  { title: "TombModel18", textName: TombModel1RawText18 },
  { title: "TombModel19", textName: TombModel1RawText19 },
  { title: "TombModel20", textName: TombModel1RawText20 },
  { title: "TombModel21", textName: TombModel1RawText21 },
  { title: "TombModel22", textName: TombModel1RawText22 },
  { title: "TombModel23", textName: TombModel1RawText23 },
  { title: "TombModel24", textName: TombModel1RawText24 },
  { title: "TombModel25", textName: TombModel1RawText25 },
  { title: "TombModel26", textName: TombModel1RawText26 },
  { title: "TombModel27", textName: TombModel1RawText27 },
  { title: "TombModel28", textName: TombModel1RawText28 },
  { title: "TombModel29", textName: TombModel1RawText29 },
  { title: "TombModel30", textName: TombModel1RawText30 },
  { title: "TombModel31", textName: TombModel1RawText31 },
  { title: "TombModel32", textName: TombModel1RawText32 },
  { title: "TombModel33", textName: TombModel1RawText33 },
  { title: "TombModel34", textName: TombModel1RawText34 },
  { title: "TombModel35", textName: TombModel1RawText35 },
  { title: "TombModel36", textName: TombModel1RawText36 },
  { title: "TombModel37", textName: TombModel1RawText37 },
  { title: "TombModel38", textName: TombModel1RawText38 },
  { title: "TombModel39", textName: TombModel1RawText39 },
  { title: "TombModel40", textName: TombModel1RawText40 },
  { title: "TombModel41", textName: TombModel1RawText41 },
  { title: "TombModel42", textName: TombModel1RawText42 },
  { title: "TombModel43", textName: TombModel1RawText43 },
];

export const tombModelTwoText = [
  { title: "TombModel44", textName: TombModel2RawText1 },
  { title: "TombModel45", textName: TombModel2RawText2 },
  { title: "TombModel45", textName: TombModel2RawText3 },
  { title: "TombModel46", textName: TombModel2RawText4 },
  { title: "TombModel47", textName: TombModel2RawText5 },
  { title: "TombModel48", textName: TombModel2RawText6 },
  { title: "TombModel49", textName: TombModel2RawText7 },
  { title: "TombModel50", textName: TombModel2RawText8 },
  { title: "TombModel51", textName: TombModel2RawText9 },
  { title: "TombModel52", textName: TombModel2RawText10 },
  { title: "TombModel53", textName: TombModel2RawText11 },
  { title: "TombModel54", textName: TombModel2RawText12 },
  { title: "TombModel55", textName: TombModel2RawText13 },
  { title: "TombModel56", textName: TombModel2RawText14 },
  { title: "TombModel57", textName: TombModel2RawText15 },
  { title: "TombModel58", textName: TombModel2RawText16 },
  { title: "TombModel59", textName: TombModel2RawText17 },
  { title: "TombModel60", textName: TombModel2RawText18 },
  { title: "TombModel61", textName: TombModel2RawText19 },
  { title: "TombModel62", textName: TombModel2RawText20 },
  { title: "TombModel63", textName: TombModel2RawText21 },
  { title: "TombModel64", textName: TombModel2RawText22 },
  { title: "TombModel65", textName: TombModel2RawText23 },
];

export const tombModelThreeText = [
  { title: "TombModel66", textName: TombModel3RawText1 },
  { title: "TombModel67", textName: TombModel3RawText2 },
  { title: "TombModel68", textName: TombModel3RawText3 },
  { title: "TombModel69", textName: TombModel3RawText4 },
  { title: "TombModel70", textName: TombModel3RawText5 },
  { title: "TombModel71", textName: TombModel3RawText6 },
  { title: "TombModel72", textName: TombModel3RawText7 },
  { title: "TombModel73", textName: TombModel3RawText8 },
  { title: "TombModel74", textName: TombModel3RawText9 },
  { title: "TombModel75", textName: TombModel3RawText10 },
  { title: "TombModel76", textName: TombModel3RawText11 },
  { title: "TombModel77", textName: TombModel3RawText12 },
  { title: "TombModel78", textName: TombModel3RawText13 },
  { title: "TombModel79", textName: TombModel3RawText14 },
  { title: "TombModel80", textName: TombModel3RawText15 },
  { title: "TombModel81", textName: TombModel3RawText16 },
  { title: "TombModel82", textName: TombModel3RawText17 },
  { title: "TombModel83", textName: TombModel3RawText18 },
  { title: "TombModel84", textName: TombModel3RawText19 },
  { title: "TombModel85", textName: TombModel3RawText20 },
  { title: "TombModel86", textName: TombModel3RawText21 },
  { title: "TombModel87", textName: TombModel3RawText22 },
  { title: "TombModel88", textName: TombModel3RawText23 },
  { title: "TombModel89", textName: TombModel3RawText24 },
];

export const tombModelFourText = [
  { title: "TombModel90", textName: TombModel4RawText1 },
  { title: "TombModel91", textName: TombModel4RawText2 },
  { title: "TombModel92", textName: TombModel4RawText3 },
  { title: "TombModel93", textName: TombModel4RawText4 },
  { title: "TombModel94", textName: TombModel4RawText5 },
  { title: "TombModel95", textName: TombModel4RawText6 },
  { title: "TombModel96", textName: TombModel4RawText7 },
  { title: "TombModel97", textName: TombModel4RawText8 },
  { title: "TombModel98", textName: TombModel4RawText9 },
  { title: "TombModel99", textName: TombModel4RawText10 },
  { title: "TombModel100", textName: TombModel4RawText11 },
  { title: "TombModel101", textName: TombModel4RawText12 },
  { title: "TombModel102", textName: TombModel4RawText13 },
];
