import React, {useState} from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Akant.module.css'
import { akantText } from '../../GalleryData/AkantCarouselData.js'

export default function Akant() {
  const [textArrayIndex, setTextArrayIndex] = useState(0);
    function prevText() {
       if (textArrayIndex > 0) {
      setTextArrayIndex(textArrayIndex - 1);
    } else {
      setTextArrayIndex(akantText.length - 1);
    }
}

    function nextText() {
      if (textArrayIndex < 12) {
      setTextArrayIndex(textArrayIndex + 1);
    } else {
      setTextArrayIndex(0);
    }
}

const RawText = akantText[textArrayIndex]["textName"];


  return (
      <div>
          <Head>
            <title>sara_deniz_akant ~ how_t_langed — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>


          <Header headerBackground="akantBackground"/>

          <div className={styles.container}>

          <div className={styles.carousel}>
          <div className={styles.prev} onClick={prevText}>&#x29CF;<br/>&#x29CF;<br/>&#x29CF;</div>
          <div className={styles.next} onClick={nextText}>&#x29D0;<br/>&#x29D0;<br/>&#x29D0;</div>
          <div><RawText/></div>
          </div>

           </div>




              <Footer/>

                    </div>

                      )
                    }
