import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Alternate.module.css'

export default function Issue3() {
  return (
    <div className={styles.container}>
    <html className={styles.fullPageBackground}>
      <Head>
        <title>new_sinews issue3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

        <body className={styles.pageStructure}>

    <div className={styles.titleAndSubtitle}>
      <div className={styles.pageTitle}>n <i>e </i>w __   <span
      className={styles.inverseTitleColor}>  s <i>i</i> n</span><br/>  __  e<i> w </i> s</div>
      <div className={styles.issueTitle}>i<br/> s<br/> s<br/> u<br/> e <br/><br/>      <span
      className={styles.inverseSubtitleColor}>t<br/>h<br/>r<br/>e<br/>e</span></div></div>

      <div className={styles.issueContents}>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">vi khi nao_retrieve the dusk</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">cary stough_balance sheet</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">sara deniz akant_how t langed</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">steven alvarez_data blood // zero progress silhouette</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">megan jeanne gette_summoning green, a leprosy of the heart</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">kelly krumrie_excerpts from ‘no measure’</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">shome dasgupta_remember nothing</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">mike corrao_ovidian dynamics</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">~~~ contri butor_ _ _b  i  os ~~~</a>
        </div>
        </div>

 </body>
</html>
</div>

  )
}
