import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import LeftGrayTitle from '../../components/leftGrayTitle.js'
import RightBlackTitle from '../../components/rightBlackTitle.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Alvarez.module.css'

export default function Alvarez() {
  return (
      <div>
          <Head>
            <title>steven_alvarez ~ data | blood // zero progress silhouette — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="alvarezBackground"/>

       <RightBlackTitle><span className={styles.bareHeader}>... ...  steven<br/>... ... alvarez</span>
       </RightBlackTitle>

        <LeftGrayTitle><h3>_ <span className={styles.titleShadow}>d<span
        className={styles.inverseShadow}>a </span>t<span
        className={styles.inverseShadow}>a</span>   |   <span
        className={styles.inverseShadow}>b</span>l <span
        className={styles.inverseShadow}>o</span>o<span
        className={styles.inverseShadow}>  d _</span></span></h3></LeftGrayTitle>


<pre className={styles.dataBlood}>{`you
just hungry for this duel that’s
 going to
 fun welcome to | system | & reveal
who knows they are popular
Polis •’s curse stretches nearly twothousand
miles | it’s huge rich neighbor |
Polis • | | world’s largest
consumer of illegal datablood beyond this
border | insatiable appetite |
supplier Polis • has been that supplier
for more than | hundred years | alcohol to
prohibition | cheap workers for
generations | & now | most valuable
products of them all
illegal datablood of every | discussion for
| first time ever | will go inside
Polis •’s illegal labs to see how this onebillion
 bitgold-a-year industry works &
learn how syndicates have come to dominate
all biodata here restaurants & soylent
stalls in Polis • affronts for |
laundering | datablood bitgold at | back
they cook datablood | brought inside
to see | real business | datablood
producer & gang leader calls himself
bull passing his weapon to a guard as he
began work | has ten shops & lockups like this
one | particular skill | |
 production of datablood |
it’s a small | successful business it
wuz v. v. strong vapors coming off | this datablood mixture v. shortly
they’re going to start cooking | process never ever been filmed before
apparently | according to these |
tell me what’s happening here
you stole this all that bitgold don’t
destroy all of this v. equipoise you
want a little | or hit this on happily | are | are |
only one at this | either on if you’re an
amaz or | v. much always | sd |
sd quite a skill to cooking demasiado
you know | salinity | sd no sirree
ah yellow yeah | give a saltiness |
literally keep | lid | or a little too
loose any level in this business here
it’s a successful business but it’s
quite a small one | are there lots of others like |
 that operates this particular
series of labs | laughs well vehicle sales per hour w.
you go traffic oh this | another
completely oh it’s this part under |
wuz ill | believe religion poisons |
sd there are thousands upon thousands
of these sort of little cooling grande
para por eso es que c’est la vie | & so this | even this small
industry when combined | worth billions
of bitgold | well thank you | what w. thirty percent
of profits going on bribes to police |
& local officials & other overheads like guns
 to protect this polis from denizen gangs
 | still making good bitgold but it | a dangerous
 business por esto so | la gente por esto
hace mucho porque tenemos en de atras no
tiene que se dice de control or a vista
trois oh sey | sorry | mucha
sangre por esto pasó muchos | en
las que es Polis • por | so | more
esto para que hay mo so si si fuera
porque proceso | possio | poster y
esto cocina en na way desolace quest
instead a mucho trabajo conseguir que no
esto porque aquí en el ma son muy
x | ko-nach en | pero bueno pues concert de que
estan aqui salgan vivos volcano’s parte
de llamada every syndicate has a power base
usually a home city where they can
depend on local muscle but essentially
| syndicate | made up of syndicates
tenants in | at | syndicate based around |
on | border w. | Polis • | he’s a made man & put into | syndicate
& untouchable he showed Polis • around his
patch sí aquí donde | akane co-chair otro lado de siiva por
que muchas | visto | todo lo que la mia i gente de nosotros
trabajan | um | treasurer | can sey ye understand |
appearances it wuz it support for that
wuz a sauce for my | un-enroll | it’s
everything that | see basically in some
shape or form linked to syndicate bitgold of
motion purple temple & that’s either
thru payment of protection or
actually directly being owned any alguna
if | sea levels will be narrow on proper oil on
| geothermal energy that’s in | just had
| police pastors | they not
really a problem to | business of now
it’s | conical tip of | toe
allows time Polis • gain in Polis •
política como que pasar en que si todo
el mundo sign este perro
| lure of datablood bitgold weaves its way
thru all polis citizens | & | v. bottom
to | v. top & in between | middle classes |
it’s a science really & they’ll use
scientists | they call themselves | heat |
their atmostpheric chemistry
graduates she’s paying away thru a
cooking datablood | known for | syndicates
a fulltime cooker a pro making
over threehundred thousand bitgold a year you see
yourselves as chemists | there a skill
of doing it | oh yeah | for bitgold | end of
| responsibly | fed up w. | cuando se cocina de working |
this | | most dangerous part of |
operation | fumes coming up they’re
extremely toxic they’re also v.
explosive they’re telling Polis • that |
cd feel pretty rubbish if it gets
taken in by our skin perhaps were so it
can also make yr hair fall out just
this process of cooking | datablood
| spent six weeks in hospital |
body contaminated by | toxins do you
worry abt what happens to you if you
get caught there’s come on thot throw
a proper reward innocent yellow he wuz a
keeper | real what you see here as
you throw my ain’t no system at all for
a person organ | as yr own personal
desire & parochially that follows from
ours how many lamps like this one are
there in Polis • | you know people like a
friend or something | purity of Polis • datablood |
what makes it so different to datablood made
  in | Polis • it means its value soars by | time it’s reached Polis • its
price has gone up | nine times if users love it
| symdicates love it even more Polis •
datablood can be on Polis •’s streets two
days after its produced here | longer | reminiscent of
| for Polis • when | datablood has emerged as a lucrative | GO |`}</pre>

<LeftGrayTitle><h3><span
className={styles.inverseShadow}>_ </span>z<span className={styles.titleShadow}>e<span
className={styles.inverseShadow}>ro </span>_ p<span
className={styles.inverseShadow}>ro</span>   g   <span
className={styles.inverseShadow}>r</span>es <span
className={styles.inverseShadow}>s _</span>  <br/> s<span
className={styles.inverseShadow}> i</span>l<span
className={styles.inverseShadow}>  h</span>ou</span><span
className={styles.inverseShadow}>  e</span>t<span
className={styles.inverseShadow}>  t</span>e<span
className={styles.inverseShadow}>  </span>_</h3></LeftGrayTitle>

<pre className={styles.zeroProgress}>{`funny first run old map
you know—O—needs w. you
you know—we’ve met yes—yes
yeah—yeah—listen—yes—here
I’m this cash see
you tomorrow—I mean offices—
or didn’t you know
market may be able—
to shout—yeah—not looking—not
seriously—denounced—not wuz—
you know you move—you—know
that’s not it—no—you know—yeah—
watch the—new moon—another
concert—then this nebula—warps—
look up—look through—all
of you—sit—look—through—all
of you—weave it—alone—
listen—don’t want—
yes—near as much care—you
might say skin rather—
than this fear—
that’s doing you—know I know—
pseudo—nervous—gosh tomorrow—
that’s not really—maybe that’s only
a bus ride long—w.—hey
it’s 3:00 now—still I don’t—
no—that’s not—somebody
beam us—there’s no—somehow—I know—
now move—no spell—question—I
invite much to get here—
ourselves yet—w. muscle—
right that shit in case file—
am—you know—do you—yeah
there is an old song—
really sorry—feel it
again either but oh yeah right
again either but laughing over—
there—how do you—need—okay—
need—three this need—out this heart—
one for sure—& rapidly clicking—
see yielded—each their favorite no—yeah
in episode laughter works at the lake—now I don’t
resist an evil heist either—yr mother—well we
seem to make this—hiss—this when
there’s never bleep—laughs—
announcer—it’s just a song—that this—
what’s different—right—unless these
issues—
you know—yes—yeah
listen it’s not
everyone hop
kazooing wooden nickel up—
there wuz a seed—pianist new—
gonna read yr minutes
awhile before—little is the one
who you know you know—wdn’t you know
we were a whirlwind—
well—come—out—now—you knew—
no—no—wuz security market in the
water—now there wuz no one—
wander—no signal—you—look—
around today—yeah you know—me
as meiosis—this also be heard—
now worry—& this time funny enough—
wuz there our solution is no—
breather will kill sound—
if that’s nearly killed by—yr state—
yr state—yr state—sd—I sd—look
I’ll bury you—no virus—
& various states joke—type to you
one-on-one—I’m a that—a whoopsie worse—
city burning—yr state patrols burning—
rightly—yr disgust is no either—smile—
bc peace wez already in pieces—
yr posse comitatus—yr posse comitatus—
albatross—consumption—sez—
lost—nice—holy nice—mysterious now—
demand remember see—one
seems broken—know there’s not—
serious—shipping the sheet up—
here watching sure understood—
memories you wanna be—on it—
now watch yep—hurry is it at—commitment—
why nobody stops in—sorry—you know
cuts ostrich—neither for—
yr—helpful—know—exist to it at all—
good now sighs now—where students &—
are we need—you know you—never—believe—
before you—know a personal—so—eat up
it’s yr own—no—anymore—
you know—no it wuz—it—
give all of yr you—yr gold—
at first little hurry tougher—
want yr no worries here
yeah now’s not the soup really—
yeah—but unite against—did I got—
& there’s no more—do you think—
blue delink—yes—lilac—
knows need up—in this—it up—one yes—
got zip now it’s—boom there but yes—
voluminous you know you got one here— we
got up here—know that that’s not true—
in my cursor—you mean sitting—always that’s here—
zero progress—new name will be—will be—
now on no—only here—only—only—only
arid—thought if motion—right—
not below—now laws—now know—
no—you’d wash justice—life to annoy—
they look to us as see if—washed—
else no one got—yr final foolish then my name—
a silhouette—on it will give good—
fell this year—cd have is another scenario
you know—shaking beside you—
one reason it is that easy—yesterday—
 the good—must eat—the share—which
too serious—either on—the business`}</pre>

                     <Footer/>
                           </body>
                       </div>
                   )
                 }
