import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import LeftGrayTitle from '../../components/leftGrayTitle.js'
import RightGrayTitle from '../../components/rightGrayTitle.js'
import StandardLineation from '../../components/standardLineation.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Dusk.module.css'

export default function Dusk() {
  return (
      <>
          <Head>
            <title>vi_khi_nao ~ retrieve_the_dusk — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

       <Header headerBackground="duskBackground"/>

       <body>

        <LeftGrayTitle><h3><span className={styles.duskShadow}>Ret<span
        className={styles.inverse}>r</span>iev<span
        className={styles.inverse}>e</span> T<span
        className={styles.inverse}>h</span>e D<span
        className={styles.inverse}>u</span>s<span
        className={styles.inverse}>k</span></span></h3></LeftGrayTitle>


        <RightGrayTitle><span className={styles.bareHeader}>——vi khi<br/>nao</span>
        </RightGrayTitle>


        <StandardLineation content={`

  1.
  They all met in the café.
  Their cheeks burn like roses.
  Each grabs a chair leaning against a table.
  They share it like a circle of seduction.
  The men sip their gin.
  Citric on the rim.
  The cocktail glasses for the women.
  Later there will be cocks all over them.
  There will be the sweet rhyme of the engine.
  Of the planks and of their bodies underneath the procreative engine.
  Underneath water.
  She sleeps so deeply      the crescent of desire inside her.
  Laterally.
  I get excited when it comes to you.
  I am sorry but I like you.
  She doesn’t know how to devour or at what angle to take her yet.
  Like the body slipping down the mind in order to retrieve the dusk.
  The sun was falling rightly and the phone kept on hitting my face.
  Crescent textures I could not see.
  The clerk who helps us, a blond girl with hair short very short. Very beautiful, luminous eyes. She
  suggested that biscotti must be drank with coffee.
  She offered coffee but I don’t drink coffee so I declined.
  Biscotti is hard and can be scraped off. I wouldn’t need to brush my teeth after this. The luminous
  eye girl caresses my hand subtly.
  Everywhere the sun is kissing the light.
  There are drops around the rim of the terrace.
  Light overwhelms.
  The leg brushing against desire, where a table can’t stand.
  After the skin burns with beauty and desire, what else is there to see?
  The declining hill of her lush tongue over the metal blade.
  The afternoon drops her skirt of sunlight.
  Dusk falls over the earth.
  Everyone should be naked and dark and exposed to a thin glass of shade.
  Even in amber, the heart will mow away every verdant blade of envy, so there is nothing for the
  heart to do but absorb bliss.
  After this the mind unclothes its formality of sensuality.
  Even the tongue couldn’t escape.
  Your glances are captivating all of my side glances.
  In October of that year, the winter shreds all of her shadows of sunlight.
  In the room, the polyamorous fruits are dropping on the floor.
  Even the glass cannot hold the body that is bending over.
  The body of tulip and sun light as they fall over the table.
  The carpet with its resilient shade of nostril remains quiet.
  Inside her face, something is reclining.
  The afternoon surrenders.
  In the evening the men unclothe.
  Their members become hard as wood.
  The madera is tossed into the fireplace.
  Like oak or was it walnut that can keep the fire going even after four hours of seduction. From
  wood to ash.
  Of reduction. From wood to ash.
  Even on the fireplace the sound of the sea is moving into the room.
  Fire in the large scheme of life on the beach becomes the smallest tongue that flirts with the wind.
  Nostril to coastline.
  Her sweat hides inside her polyvocal scarfs.
  A fire escapes into the house.
  The right side of the room is eating away all the melancholy.
  Even breath is anchored in suffocation.
  On Sunday the earth tosses its black shirt in the air.
  The world is naked above the hip.
  The men are laughing with their hearts floating in and out of the sleeves of their shirts.
  Who knows what will happen to their beard.
  Who knows if their five o’clock shadow is mow-able?
  Their eyes are a million miles away.
  Even the legs of the chairs will have to wear winter socks.
  When asked if the kiss will sink, the reply:
  Everyone will remember that the pasta dish is filled with truffle oil.
  The bartender drops a spoon on the floor.
  Ears perked up like rabbits.
  Marie’s eyes are moving across the landscape.
  The wind is inviting the men to come outside where the basil plants nearly fall fatally over from
  the cold.
  They continue to talk. They agree based on the eyes of other eyes that they won’t be going
  outside to face the cold.
  They don’t want to be bottles of champagne chilled in ice buckets.
  They wind will make them feel like so.
  They try to converse.
  Suppose they were able to exchange seats with the men and be shoulder to shoulder.
  Marie smiles and turns her head towards the direction of the bar.
  The bartenders are flipping and shaking the canteens, where a pineapple slice hides its smile.
  Alex turns her heads away.
  The long thighs of other women are hiding beneath the winter coats.
  Their thin trench coats.
  To protect them from the wind.
  Marie slips into the bathroom.
  Alex sits back and studies the contours of the bar booth.
  Everything is luxurious.
  Different symmetry to the history of sex.
  And the sea is drifting away.
  They have gazed long into the sentences hiding beneath their skirts.
  They knew the men are fucking them.
  Opening and closing.
  They feel closer to mussels than ever before.
  Closer to the muscles of mussels than ever as the men fuck them.
  They thought of clams and the different layers of octopus flesh.
  Alex turns her gaze toward Marie’s as Malix fucks her.
  There is a certain rhyme to this fuck.
  The way she has been handled.
  Her breasts being pushed forward by his chest.
  As if her breasts were trying to climb over to her face, but have to cross the bridge of her neck.
  She remembers her soul on the coat hanger.
  Someone is taking it away as she walks her self away.
  Alex catches her by the sleeves.
  And Marie is giggling deep into the snow bank of her cocktail.
  Something in her is disappearing.
  As the different creatures poke around her.
  Marie is drifting.
  As the sound of the waves clash against the rock.
  And Marie smiles at her sadly.
  The different textures of the shadows.
  Fleeing and escaping on the walls and ceiling.
  They toss their shadows forward.
  Her kidney will sink down on him.
  Alex finds Marie’s gaze. A small gaze at the corner of the universe.
  Marie feels her heart is going to go in reverse.
  Connor presses his lips on Marie.
  Marie turns her face. Alex turns her face away from all faces.
  Marie’s gaze softens.
  The whole room is going to suffer.
  The kisses are dashing all over the place.
  There is certainty in the breasts being probed.
  They take turns slipping in and out of the room just as Marie is slipping into Alex’s gaze.
  The coffee table is acutely dark. In its cherry coating.
  No one is thinking about the circumference of the room.
  Nor the rim of the glass.
  No one knows where he or she can take each other.
  Around the room in tight circles of darkness.
  There are only the contours of penetration, where no one understands but everyone perceives.
  And the exactitude of the plunge.
  Different body parts are swelling.
  A common smell of sex and pasta aftertaste.
  No one knows where the capers have disappeared?
  And if the mussels have weakened their muscles.
  Malix and Connor are laughing.
  Their throats are like volcanoes.
  Marie gazes at Alex.
  Alex smiles softly before turning her gaze elsewhere.
  There is a small space where their eyes are linked.


  2.
  The room spins and each head is turning in one direction to another.
  Legs are swinging.
  The heels are tapping the floor.
  Men tapping their shoes.
  All above the size of ten except one.
  One man in size eight, but he has the confidence of the bathroom tissue.
  He leaves with two women in his arms.
  When their bodies are this way, they become coffins.
  Maybe having sex was like having bodies turned into coffins.
  Fucking becomes a gate in which the soul finds an exit point to slip out of the body.
  This kind of intercourse—it was hard to remember what it is like for the bodies to lie like planks
  against the ground.
  Something in them widens.
  Transfixed.
  Legs wining beneath the table.
  Women silence their pleasure as the men moan over them.
  MARIE: I have a table cloth I want you to have.
  Alex turns her gaze away as the men climb over them.
  Alex turns to Marie.
  ALEX: My mother scrubs her celery sticks with a brush. The only way to really get the soil off
  them.
  Her breasts are bobbing up and down.
  MARIE: Let me put your smile into my purse and open it a little later.
  She derives great pleasure from handing her documents over to the clerk.
  In the morning the men get dressed and the women get dressed.
  Alex walks over to Marie.
  Drops on her knees as if to genuflect.
  As soft as light.
  And then her nose descends as it becomes parallel to the belly button.
  She leans in.
  Alex listens to the high heels dropping away.
  ALEX: If I give you a tablecloth, would you accept it?
  Her gaze toward Marie is soft as dew.
  Frame by frame, the subcultural tenderness is exposed to light.
  MALIX: Why don’t you take Marie into your mouth?
  ALEX: At what point will the bus stop?
  Some parts of Malix’s shoulder is censoring Marie’s gaze.
  As the wind is being blown back into the room.
  Push the belly button of time through your reality.
  Is love an empty device of snow?
  Is love an empty device of sorrow?


  3.
  The night lasted a long time in her mouth.
  I tuck the experimental books away and the horse postcard from France.
  I don’t think I am poking the elusive legs of darkness.
  This dream is sweet.
  The song keeps running the current over my face.
  Each cup is floating down the street.
  I phoned my mother. Told her about the café girl with beautiful luminous eyes.
  And there is so much transcendence.
  And then the rim of the mouth.


  4.
  Once in a while while someone is standing still the moon sits on someone’s heart.
  She begins to code her ordinary language with her meaning as if to avoid the inner seam of being
  discovered.
  I sit better


  5.
  I sat there on the sofa futon reading all day and not breathing.
  You think the night could slip into your face and your face can fall asleep.

  “Now all I can do is breathe like the vegetables in the garden. I have a physical longing for you.”`}/>

  <br/><pre className={styles.italAnomaly}>  The Land of Green Plums.</pre><StandardLineation content={`


  6.
  Her arms are waterhoses, inflated.
  No one can ever brush his face under the rug.


  7.
  Tomorrow I will eat eggs.
  And there is a little bit of cranberry juice left.
  The grapes were so pure and delicious.
  Julia wanted to watch me eat.
  Helia is dropping the room in everyone’s lap.
  Everyone is so beautiful.
  Their ears are slipping down to their arms.
  Even the biceps are listening onto the conversation.
  I feel closer to Helia because of this event.


  8.
  Her father will fly and she will be heading to New York.
  I hope all the best for her.
  As she travels far and wide.


  9.
  She has been cutting the poppycakes in segments.
  I hope it is large as my mouth is not fitting in.
  It hasn’t registered to me yet that it will be awhile deep in the distant of the future.
  I won’t see her again.
  But I feel so sad.
  Sad.
  All goodbyes without having a permanent relation.
  Helia told me that she had a hard time she didn’t want to wash the saucer.
  And the teacup because of the extremely rare vortex of my fortunes.
  So she let it sits and just stared at it longer.
  She is holding my fortunes in her eyes for a little longer.
  And this is at the edge of existence.
  I smell the perfume in the clearing.
  As people are slipping away and there is no need to wave the air.
  Cut the button off the shirt and drop it down the well of the lungs.
  Or drop it down the well of the asshole.
  It is night and perhaps I will be able to sleep.
  I remember heart heart is shaped like a cupcake.
  It is nice to know that it is fluffy and has an expiration date.
  I think I was a child when I had a night like tonight.
  Being this way.
  Staying a little longer.
  Yes, stay.
  I think it is Helia who doesn’t have an ego.
  I think Helia is egoless.
  She has grand schemes of working a lot and not getting paid.
  I wish I had grown up with a best friend like Helia.
  I’ll probably learn how to serve Turkish coffee and Turkish apricots.
  Sometimes to strangers.
  Her eyes, yes, they are burning.
  It seems all the MFA students are having health issues.
  Yes, the maternity of the year.

          `}/>



                     <Footer/>

          </body>

                       </>
                   )
                 }
