import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightGrayTitle from '../../components/rightGrayTitle.js'
import RightBlackTitle from '../../components/rightBlackTitle.js'
import StandardLineation from '../../components/standardLineation.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Gette.module.css'

export default function Gette() {
  return (
      <div>
          <Head>
            <title>megan_jeanne_gette ~ summoning_green, a_leprosy_of_the_heart  — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="getteBackground"/>

        <RightGrayTitle><h3><span className={styles.titleShadow}>s<span
        className={styles.inverseShadow}>u</span>mm<span
        className={styles.inverseShadow}>o</span>ni<span
        className={styles.inverseShadow}>ng g</span>r<span
        className={styles.inverseShadow}>ee</span>n, a <span
        className={styles.inverseShadow}>leprosy of the heart</span></span></h3></RightGrayTitle>


        <RightBlackTitle><span className={styles.authorName}>——<i>megan<br/>jeanne<br/>gette</i></span>
        </RightBlackTitle>

                     <Footer/>
                           </body>
                       </div>
                   )
                 }
