import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Issue3.module.css'

export default function Issue3() {
  return (
    <>
      <Head>
        <title>new_sinews issue3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <div className={styles.fullPageBackground}>
        <body className={styles.pageStructure}>

    <div className={styles.titleAndSubtitle}>
      <div className={styles.pageTitle}>n <i>e </i>w __   <span
      className={styles.inverseTitleColor}>  s <i>i </i> n</span><br/>  __  e<i> w </i> s</div>
      <div className={styles.issueTitle}>i<br/> s<br/> s<br/> u<br/> e <br/><br/>      <span
      className={styles.inverseSubtitleColor}>t<br/>h<br/>r<br/>e<br/>e</span></div>
        </div>

      <div className={styles.issueContents}>
        <div className={styles.workColumn}>
        <div className={styles.workLink}><Link href="/issue3/dusk">vi khi nao_retrieve the dusk</Link></div>
        </div>
        <div className={styles.workColumn}>
          <div className={styles.workLink}><Link href="/issue3/stough">cary stough_balance sheet</Link></div>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">sara deniz akant_how t langed</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">steven alvarez_data blood // zero progress silhouette</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">megan jeanne gette_summoning green, a leprosy of the heart</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">kelly krumrie_excerpts from ‘no measure’</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">shome dasgupta_remember nothing</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">mike corrao_ovidian dynamics</a>
        </div>
        <div className={styles.workColumn}>
          <a className={styles.workLink} href="">~~~ contri butor_ _ _b  i  os ~~~</a>
        <div className={styles.siteShortcuts}>
              <button className={styles.linkButton}><a
              className={styles.innerSiteLinkTag} href="https://newnewsinews.com">new sinews</a></button>
              <button className={styles.linkButton}><a
              className={styles.innerSiteLinkTag} href="https://newnewsinews.com/about">about</a></button>
              <button className={styles.linkButton}>
                <a className={styles.twitterLinkTag} href="https://twitter.com/new_sinews">[Bird App]</a>
              </button>
              </div>
          </div>
        </div>

 </body>
</div>
</>

  )
}
