// > 75 Grid
const highTempGrid = {
  physiologicalState: {
    0: "Loose-",
    1: "Expan-",
    2: "Grow-",
    3: "Full-",
    4: "Slake-",
    5: "Jitt-",
    6: "Puls-",
    7: "Bas",
    8: "Slith-",
    9: "Ener-",
  },
  affectiveState: {
    0: "-bauch-",
    1: "-furi-",
    2: "-cruel-",
    3: "-venge-",
    4: "-elait-",
    5: "-flir-",
    6: "-joys-",
    7: "-interess-",
    8: "-curi-",
    9: "-urge-",
  },
  subjectDeclension: {
    0: "-my-edges",
    1: "-blanks",
    2: "-my-worlds",
    3: "-foods",
    4: "-my-works",
    5: "-others",
    6: "-my-selves",
    7: "-spaces",
    8: "-my-senses",
    9: "-threats",
  },
  subjectConjugation: {
    0: "my-",
    1: "blank-",
    2: "my-",
    3: "food-",
    4: "my-",
    5: "other-",
    6: "my-",
    7: "space-",
    8: "my-",
    9: "threat-",
  },
  prefix: {
    0: "-supra-",
    1: "-epi-",
    2: "-re-",
    3: "-post-",
    4: "-extra-",
    5: "-inter-",
    6: "-ultra-",
    7: "-ever-",
    8: "-over-",
    9: "-be-",
  },
  verb: {
    0: "-gnash-",
    1: "-stroy-",
    2: "-boil-",
    3: "-thrash-",
    4: "-flay-",
    5: "-prowl-",
    6: "-rip-",
    7: "-swall-",
    8: "-blare-",
    9: "-laugh-",
  },
  direction: {
    0: "-in",
    1: "-up",
    2: "-out",
    3: "-way",
    4: "-wards",
    5: "-ful",
    6: "-left",
    7: "-ight",
    8: "-down",
    9: "-back",
  },
  subjectConjugation2: {
    0: "my-edge",
    1: "blankings",
    2: "my-world",
    3: "foodings",
    4: "my-work",
    5: "othereds",
    6: "my-self",
    7: "spacings",
    8: "my-sense",
    9: "threatings",
  },
  verb2: {
    0: "sprawl",
    1: "exude",
    2: "sing",
    3: "glott",
    4: "furl",
    5: "rave",
    6: "spread",
    7: "spray",
    8: "faunt",
    9: "pierce",
  },
  object: {
    0: "seed-",
    1: "water-",
    2: "air-",
    3: "drople-",
    4: "nitroge-",
    5: "silt-",
    6: "sunligh-",
    7: "night-",
    8: "vapor-",
    9: "tract-",
  },
  objectOrientation: {
    0: "-speck",
    1: "-part",
    2: "-entire",
    3: "-surface",
    4: "-core",
    5: "-angle",
    6: "-slant",
    7: "-tip",
    8: "-top",
    9: "-heft",
  },
  qualityAdjective: {
    0: "blue-",
    1: "gold-",
    2: "light-",
    3: "scrit-",
    4: "clear-",
    5: "lumin-",
    6: "sharp-",
    7: "bright-",
    8: "ribe-",
    9: "soft-",
  },
  transitionAdverb: {
    0: "-with",
    1: "-so",
    2: "-thus",
    3: "-long",
    4: "-well",
    5: "-ly",
    6: "-then",
    7: "-past",
    8: "-ward",
    9: "-fore",
  },
};

// 55 - 75+ Grid
const midTempGrid = {
  physiologicalState: {
    0: "Cling-",
    1: "Throb-",
    2: "Thirs-",
    3: "Crave-",
    4: "Scurv-",
    5: "Conser-",
    6: "Withol-",
    7: "Scroun-",
    8: "Balan-",
    9: "Equi-",
  },
  affectiveState: {
    0: "-fraid-",
    1: "-terrie-",
    2: "-worrie-",
    3: "-needeed-",
    4: "-scare-",
    5: "-autious-",
    6: "-quare-",
    7: "-irritay-",
    8: "-errulous-",
    9: "-ervey-",
  },
  subjectDeclension: {
    0: "-mineledges",
    1: "-blanks",
    2: "-mineworlds",
    3: "-foods",
    4: "-mineworks",
    5: "-others",
    6: "-mineselves",
    7: "-spaces",
    8: "-minecores",
    9: "-threats",
  },
  subjectConjugation: {
    0: "mine-",
    1: "blank-",
    2: "mine-",
    3: "food-",
    4: "mine-",
    5: "other-",
    6: "mine-",
    7: "space-",
    8: "mine-",
    9: "threat-",
  },
  prefix: {
    0: "-en-",
    1: "-ex-",
    2: "-im-",
    3: "-de-",
    4: "-un-",
    5: "-semi-",
    6: "-anti-",
    7: "-mid-",
    8: "-fore-",
    9: "-under-",
  },
  verb: {
    0: "-curl-",
    1: "-sheave-",
    2: "-fither-",
    3: "-flee-",
    4: "-save-",
    5: "-mect-",
    6: "-search-",
    7: "-hold-",
    8: "-spare-",
    9: "-grimmace-",
  },
  direction: {
    0: "-in",
    1: "-up",
    2: "-out",
    3: "-way",
    4: "-wards",
    5: "-ful",
    6: "-left",
    7: "-ight",
    8: "-down",
    9: "-back",
  },
  subjectConjugation2: {
    0: "mineledge",
    1: "blankings",
    2: "mineworld",
    3: "foodings",
    4: "minework",
    5: "othereds",
    6: "mineself",
    7: "spacings",
    8: "minecore",
    9: "threat",
  },
  verb2: {
    0: "kack",
    1: "flinch",
    2: "wince",
    3: "flush",
    4: "gnaw",
    5: "clamber",
    6: "squelch",
    7: "savor",
    8: "speckle",
    9: "collect",
  },
  object: {
    0: "seed-",
    1: "water-",
    2: "air-",
    3: "drople-",
    4: "nitroge-",
    5: "silt-",
    6: "sunligh-",
    7: "night-",
    8: "vapor-",
    9: "tract-",
  },
  objectOrientation: {
    0: "-speck",
    1: "-part",
    2: "-entire",
    3: "-skin",
    4: "-core",
    5: "-angle",
    6: "-slant",
    7: "-edge",
    8: "-top",
    9: "-heft",
  },
  qualityAdjective: {
    0: "white-",
    1: "dull-",
    2: "paque-",
    3: "murk-",
    4: "hard-",
    5: "pud-",
    6: "spat-",
    7: "rough-",
    8: "muck-",
    9: "gurn-",
  },
  transitionAdverb: {
    0: "-with",
    1: "-so",
    2: "-thus",
    3: "-as",
    4: "-well",
    5: "-ly",
    6: "-then",
    7: "-past",
    8: "-ward",
    9: "-fore",
  },
};

// < 55  Grid
const lowTempGrid = {
  physiologicalState: {
    0: "Empty-",
    1: "Froze-",
    2: "Wither-",
    3: "Crac-",
    4: "Rot-",
    5: "Sick-",
    6: "Pain-",
    7: "Nauth-",
    8: "Dry-",
    9: "Hollow-",
  },
  affectiveState: {
    0: "-bland-",
    1: "-despair-",
    2: "-skurm-",
    3: "-caught-",
    4: "-poiled-",
    5: "-piti-",
    6: "-hopeleh-",
    7: "-lost-",
    8: "-strugg-",
    9: "-gone-",
  },
  subjectDeclension: {
    0: "-mineledges",
    1: "-blanks",
    2: "-mineworlds",
    3: "-foods",
    4: "-mineworks",
    5: "-others",
    6: "-mineselves",
    7: "-spaces",
    8: "-minecores",
    9: "-threats",
  },
  subjectConjugation: {
    0: "mine-",
    1: "blank-",
    2: "mine-",
    3: "food-",
    4: "mine-",
    5: "other-",
    6: "mine-",
    7: "space-",
    8: "mine-",
    9: "threat-",
  },
  prefix: {
    0: "-min-",
    1: "-non-",
    2: "-sub-",
    3: "-dis-",
    4: "-infra-",
    5: "-pre-",
    6: "-ob-",
    7: "-in-",
    8: "-ab-",
    9: "-peri-",
  },
  verb: {
    0: "-hack-",
    1: "-cower-",
    2: "-drain-",
    3: "-wreck-",
    4: "-wail-",
    5: "-hide-",
    6: "-huddle",
    7: "-blate-",
    8: "-stare",
    9: "-falter-",
  },
  direction: {
    0: "-in",
    1: "-up",
    2: "-out",
    3: "-way",
    4: "-wards",
    5: "-ful",
    6: "-left",
    7: "-ight",
    8: "-down",
    9: "-back",
  },
  subjectConjugation2: {
    0: "mineledge",
    1: "blankings",
    2: "mineworld",
    3: "foodings",
    4: "minework",
    5: "othereds",
    6: "mineself",
    7: "spacings",
    8: "minecore",
    9: "threat",
  },
  verb2: {
    0: "-split",
    1: "-numb",
    2: "-disappear",
    3: "-weep",
    4: "-go",
    5: "-tire",
    6: "-drag",
    7: "-crawl",
    8: "-sleep",
    9: "-scrap",
  },
  object: {
    0: "seed-",
    1: "water-",
    2: "air-",
    3: "drople-",
    4: "nitroge-",
    5: "silt-",
    6: "sunligh-",
    7: "night-",
    8: "vapor-",
    9: "tract-",
  },
  objectOrientation: {
    0: "-speck",
    1: "-part",
    2: "-entire-",
    3: "-skin",
    4: "-core",
    5: "-angle",
    6: "-slant",
    7: "-edge",
    8: "-top",
    9: "-heft",
  },
  qualityAdjective: {
    0: "dark-",
    1: "numb-",
    2: "brittle-",
    3: "chorn-",
    4: "bitter-",
    5: "cut-",
    6: "worn-",
    7: "bruise-",
    8: "scarn-",
    9: "pock-",
  },
  transitionAdverb: {
    0: "-with",
    1: "-so",
    2: "-thus",
    3: "-as",
    4: "-well",
    5: "-ly",
    6: "-then",
    7: "-past",
    8: "-ward",
    9: "-fore",
  },
};

export const airPlantGrids = {
  highTempGrid: highTempGrid,
  midTempGrid: midTempGrid,
  lowTempGrid: lowTempGrid,
};
