import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import CenterGrayTitle from '../../components/CenterGrayTitle.js'
import CenterBlackTitle from '../../components/CenterBlackTitle.js'
import StandardProse from '../../components/standardProse.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Bios.module.css'

export default function Issue2Bios() {
  return (
  <div className={styles.container}>
      <Head>
        <title>issue2_bios — new_sinews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <body>

   <Header/>

   <CenterBlackTitle><h3>new_sinews</h3></CenterBlackTitle>
   <CenterGrayTitle><h3>issue_two</h3></CenterGrayTitle>
   <CenterBlackTitle><h3>contributors</h3></CenterBlackTitle>

   <StandardProse>
   <br/>
   <br/>
   SUSAN BRIANTE is the author of three books of poetry: <cite><strong> Pioneers in the
   Study of Motion</strong></cite>, <cite><strong> Utopia Minus</strong></cite>, and
   <cite><strong> The Market Wonders</strong></cite>, all from Ahsahta Press. She is
   a professor of creative writing at the University of Arizona, where she also serves
   as faculty liaison and co-coordinator of the Southwest Field Studies in Writing
   Program. The program brings MFA students to the US-Mexico border to work with
   community-based environmental and social justice groups. <cite><strong> Defacing
   the Monument</strong></cite>, a series of essays on immigration, archives, aesthetics
   and the state, will be published by Noemi Press in December 2019.
   </StandardProse>
   <br/>
   <br/>
   <br/>
   <StandardProse>
   MIKE CORRAO is the author of <cite><strong> Man, Oh Man </strong></cite> (Orson's
   Publishing) and <cite><strong> Gut Text </strong></cite> (11:11 Press). His work
   has been featured in publications such as <i>Collagist</i>, <i>3:AM</i>, <i>Always
   Crashing</i>, and <i>The Portland Review</i>. He lives in Minneapolis.
   Learn more at <a className={styles.biosExternalLink} target="_blank"
   href="http://www.mikecorrao.com/">www.mikecorrao.com</a>
   </StandardProse>
   <br/>
   <br/>
   <br/>
   <StandardProse>
   FELICIA ZAMORA is the author of the poetry books: <cite><strong> Quotient </strong></cite> (Tinderbox
   Editions 2021), <cite><strong> Body of Render </strong></cite>, winner of the 2018
   Benjamin Saltman Award from Red Hen Press (2020), <cite><strong> Instrument of Gaps </strong></cite> (Slope
   Editions 2018), <cite><strong> & in Open, Marvel </strong></cite> (Parlor Press 2018), and <cite><strong> Of
   Form & Gather</strong></cite>, winner of the 2016 Andrés Montoya Poetry Prize
   (University of Notre Dame Press 2017). She is a 2019 CantoMundo Fellow, won the 2015 Tomaž
   Šalamun Prize from <i>Verse</i>, and was the 2017 Poet Laureate for Fort Collins, CO. She received
   her MFA from Colorado State University where she teaches creative writing courses online and
   is the Associate Poetry Editor for the <i>Colorado Review</i>. She lives in Arizona and is the Education
   Programs Manager for the Virginia G. Piper Center for Creative Writing at Arizona State University.
   </StandardProse>
   <br/>
   <br/>
   <br/>
   <StandardProse>
   SAM TAYLOR is the author of three books of poems, <cite><strong> Body of the World </strong></cite>
   (Ausable/Copper Canyon), <cite><strong> Nude Descending an Empire </strong></cite> (Pitt Poetry),
   and <cite><strong> The Book of Fools: An Essay in Memoir and Verse </strong></cite> (forthcoming,
   Negative Capability). A native of Miami and a former caretaker of a wilderness refuge in New Mexico,
   he currently tends a wild garden in Kansas, where he is an Associate Professor and the Director of
   the MFA Program at Wichita State. His work has been recognized with the Amy Lowell Poetry Traveling
   Scholarship, among other awards, and his poems have appeared in such journals as <i>The Kenyon
   Review</i>, <i>AGNI</i>, and <i>The New Republic</i>.  <a className={styles.biosExternalLink} target="_blank"
   href="http://www.samtaylor.us/">www.samtaylor.us</a>
   </StandardProse>
   <br/>
   <br/>
   <br/>
   <StandardProse>
   SUSAN LEWIS <a className={styles.biosExternalLink} target="_blank"
   href="http://www.susanlewis.net/">www.susanlewis.net</a> is the author of ten books and chapbooks,
   including <cite><strong> Zoom</strong></cite>, winner of the Washington Prize, and <cite><strong> Heisenberg’s
   Salon</strong></cite>. Recently, her work has appeared in <i>Agni</i>, <i>Boston Review</i>, <i>The
   Brooklyn Rail</i>, <i>Conjunctions</i> (online), <i>Diode</i>, <i>Interim</i>, <i>New American
   Writing</i>, <i>VOLT</i>, and many other journals and anthologies. She is the founding
   editor of <i>Posit</i> <a className={styles.biosExternalLink} target="_blank"
   href="http://www.positjournal.com/"> www.positjournal.com</a>.
   </StandardProse>
   <br/>
   <br/>
   <br/>
   <StandardProse>
   REBECCA ARIEL PORTE is a member of the Core Faculty at the Brooklyn Institute for Social Research.
   She is at work on a long, wicked book about Paradise, Arcadia, and the Golden Age.
   <br/>
   <br/>
   <br/>
   </StandardProse>
   <StandardProse>
   BABAK LAKGHOMI is the author of <cite><strong> Floating Notes </strong></cite>(Tyrant Books, 2018).
   His fiction has appeared or forthcoming in <i>NOON</i>, <i>Ninth Letter</i>, <i>Green Mountains
   Review</i>, and <i>New York Tyrant</i>, among others.
   <br/>
   <br/>
   <br/>
   </StandardProse>
   <StandardProse>
   VI KHI NAO is the author of four poetry collections: <a className={styles.biosExternalLink} target="_blank"
   href="http://1111press.com/human-tetris/"> <cite><strong> Human Tetris </strong></cite></a>(11:11
   Press, 2019), <a className={styles.biosExternalLink} target="_blank" href="http://blacksunlit.com/sheep-machine/">
   <cite><strong> Sheep Machine </strong></cite></a> (Black Sun Lit, 2018), <a className={styles.biosExternalLink}
   target="_blank"
   href="https://www.journal1913.org/publications/umbilical-hospital/"> <cite><strong> Umbilical Hospital </strong>
   </cite></a> (Press 1913, 2017), <a className={styles.biosExternalLink} target="_blank"
   href="https://nightboat.org/book/the-old-philosopher/"> <cite><strong> The
   Old Philosopher </strong></cite></a>(winner of the Nightboat Prize for 2014), & of the short stories collection, <a
   className={styles.biosExternalLink} target="_blank"
   href="http://www.uapress.ua.edu/product/Brief-Alphabet-of-Torture,6637.aspx"> <cite>
   <strong> A Brief Alphabet of Torture </strong></cite></a> (winner of the 2016 FC2's Ronald Sukenick
   Innovative Fiction Prize), the novel, <a className={styles.biosExternalLink} target="_blank"
   href="https://coffeehousepress.org/products/fish-in-exile"> <cite>
   <strong>Fish in Exile </strong></cite></a>(Coffee House Press, 2016). Her work includes poetry, fiction,
   film, and cross-genre collaboration. She is the current Fall 2019 fellow at the Black Mountain Institute.
   <br/>
   <br/>
   <br/>
   </StandardProse>
   <StandardProse>
   ADAM STRAUSS lives in Louisville, KY. Most recently, poems of his appear in <i>Dream
   Pop</i>, <i>Sporklet</i>, and <i>Prelude</i>. The poems in this issue are from a chapbook
   manuscript titled <strong><cite> Syntactic Ekphrastic</cite></strong>.
   <br/>
   <br/>
   <br/>
   </StandardProse>
   <StandardProse>
   BRANDON SHIMODA's most recent books include <strong><cite> The Grave on the Wall </cite>
   </strong>(City Lights, 2019) and <strong><cite> The Desert </cite></strong>(The Song Cave,
   2018). He is the curator of the Hiroshima Library, an itinerant reading room/collection of
   books on the atomic bombings of Hiroshima and Nagasaki, which appeared at BRUNA
   press + collective in Bellingham, WA (August-October 2019), and will be taking up residence
   at the Japanese American National Museum in Los Angeles, CA, November 2019-June 2020. He
   is currently writing a book on the afterlife of Japanese American incarceration. He
   lives in the desert.
   <br/>
   <br/>
   <br/>
   </StandardProse>

   <Footer/>

  </body>
  </div>
)
  }
