import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightBlackTitle from '../../components/rightBlackTitle.js'
import LeftGrayTitle from '../../components/leftGrayTitle.js'
import StandardProse from '../../components/standardProse.js'
import StandardLineation from '../../components/standardLineation.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Corrao.module.css'

export default function Corrao() {
  return (
      <div className={styles.container}>
          <Head>
            <title>mike_corrao ~ the_archaelogy_of_virtual_spaces — new_sinews</title>
            <meta charset="utf-8"/>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="corraoBackground"/>

       <LeftGrayTitle title="the archaeology of virtual spaces"/>
       <RightBlackTitle title="... mike ... corrao ..."/>
       <StandardProse>
       The subject of my investigation is not the organism that you thought it was.
       <br/>
       <br/>
       It is an enigmatic structure.
       <br/>
       <br/>
       With rhizomatic qualities—like the mutating root of a stemless plant. The
       arrangement of low poly surfaces, each painted with pixelated textures.
       Facsimiles of stone or metal. The internal fibres of a cyborgean contraption.
       Dials and switches locked static.
       <br/>
       <br/>
       Light resting in the air, without source or duration. Extensive visibility
       across interior spaces. Even what appears external remains internal. The sky
       a curved ceiling. Haphazardly laid overhead. Painted a light blue with hues
       of white and beige crawling in. Each new room a different iteration of the
       same three colors. Only shifting in dominance and saturation.
       <br/>
       <br/>
       Movement through the structure is made difficult through the ubiquity of
       its surfaces. Each wall fluctuating between only three possible designs.
       The researcher—whatever kind of subject you have decided to be—asked to
       memorize the simplistic patterns they form when placed in succession.
       Navigating by foot through chains of corporealized data. What grows in
       the veins of the machinery. Server towers moan in the distance.
       <br/>
       <br/>
       </StandardProse>
<StandardLineation
content={` (it does not need to be this way. it is not necessary that we experience space as it asks
  us to. that we move through labyrinthine trenches. acquiring certain keys and passcodes

         a series of multi-colored dreams. landscape of the body. as it is projected onto this
      abstract mechanism

         we can refuse. stand further away. remove ourselves. or disregard what we have been
      asked to do. the constraints we have been asked to adhere to)

      CERTAIN TOOLS ARE GATHERED AND TESTED / MADE USEFUL

      MANIPULATIONS OF THE TEMPORAL / VISION SPANNING THE ARCHIVE

      REPLICATED GLITCHES TO EVADE BOUNDARY WALLS

      UN-CORPOREALIZATION / I CANNOT FEEL / I CANNOT BE FELT

      COMPRESSION AND DECOMPRESSION OF THE IMAGE ARTIFACT

      INTRUSION UPON HIDDEN CODE LANGUAGES / PROPHETIC SCRIPT

      MODIFICATION OF THE VIRTUAL BODY / BECOMING-SPECTRE

         `}/>

              <Footer/>
                    </body>
                </div>
            )
          }
