import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Issue2.module.css'

export default function Issue2() {
  return (
    <div classNameName={styles.container}>
    <html className={styles.fullPageBackground}>
      <Head>
        <title>new_sinews issue2</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <body className={styles.pageStructure}>

      <div className={styles.pageTitle}>n<i>e</i>w  _   <span className={styles.inverseColor}>s<i>i</i>n</span>  _  e<i>w</i> s</div>

    <div className={styles.issueContents}>
      <div className={styles.issue}><span className={styles.inverseColor}>i</span> s <span className={styles.inverseColor}>s</span> u <span className={styles.inverseColor}>e</span>   _   <span className={styles.inverseColor}>2</span></div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">susan briante_two poems</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">felicia zamora_selections from 'quotient'</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">christa romanosky_three poems</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">mike corrao_the archaeology of virtual spaces</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">vi khi nao_2 eyes in 1 eye: a delirium</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href=""
        >even flesh seems a formality<br/>or: vi khi nao's organic
          oscillations
        </a>
        <a className={styles.workLink} href="">~~~b  i  os ~~~</a>
      </div>

      <div className={styles.siteShortcuts}>
            <button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com">new sinews</a></button>
            <button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com/about">about</a></button>
            <button className={styles.linkButton}>
              <a className={styles.twitterLinkTag} href="https://twitter.com/new_sinews">[Bird App]</a>
            </button>
        </div>
    </div>
 </body>
</html>

      </div>
  )
}
