import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Issue2.module.css'

export default function Issue2() {
  return (
    <div classNameName={styles.container}>
    <html className={styles.fullPageBackground}>
      <Head>
        <title>new_sinews issue2</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <link rel="icon" href="../public/images/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <body className={styles.pageStructure}>
    <div className={styles.titleAndSubtitle}>
      <div className={styles.pageTitle}>n<i>e</i>w  _   <span className={styles.inverseTitleColor}>s<i>i</i>n</span>  _  e<i>w</i> s</div>
      <div className={styles.issue}><span className={styles.inverseTitleColor}>i</span> s <span className={styles.inverseTitleColor}>s</span> u <span className={styles.inverseTitleColor}>e</span>   _   <span className={styles.inverseTitleColor}>2</span></div></div>

    <div className={styles.issueContents}>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">susan briante_two poems</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">felicia zamora_selections from 'quotient'</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">sam taylor_five poems</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">rebecca ariel porte_some portraits of persons as imaginary cities</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">adam strauss_five poems</a>
      </div>
      <div className={styles.col1}>
        <a className={styles.workLink} href="">brandon shimoda_excerpts from ‘tomb model of a noble’s house’</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">mike corrao_the archaeology of virtual spaces</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">susan lewis_two poems</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">babak lakghomi_two stories</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">vi khi nao_le yeaste</a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href=""
        >saluting a hex of gangrenous sky<br/>or: brandon shimoda's ritual inversions
        </a>
      </div>
      <div className={styles.col2}>
        <a className={styles.workLink} href="">~~~ contri butor_ _ _b  i  os ~~~</a>
      </div>

      <div className={styles.siteShortcuts}>
            <button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com">new sinews</a></button>
            <button className={styles.linkButton}><a
            className={styles.innerSiteLinkTag} href="https://newnewsinews.com/about">about</a></button>
            <button className={styles.linkButton}>
              <a className={styles.twitterLinkTag} href="https://twitter.com/new_sinews">[Bird App]</a>
            </button>
        </div>
    </div>
 </body>
</html>

      </div>
  )
}
