import React, {useState} from 'react'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/LeYeaste.module.css'
import { leYeasteText } from '../../GalleryData/LeYeasteCarouselData.js'

export default function LeYeaste() {
  const [textArrayIndex, setTextArrayIndex] = useState(0);
    function prevText() {
       if (textArrayIndex > 0) {
      setTextArrayIndex(textArrayIndex - 1);
    } else {
      setTextArrayIndex(leYeasteText.length - 1);
    }
}

    function nextText() {
      if (textArrayIndex < 6) {
      setTextArrayIndex(textArrayIndex + 1);
    } else {
      setTextArrayIndex(0);
    }
}

const RawText = leYeasteText[textArrayIndex]["textName"];


  return (
      <div>
          <Head>
            <title>vi_khi_nao ~ le_yeaste — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>


          <Header headerBackground="leYeasteBackground"/>

          <div className={styles.container}>

          <div className={styles.carousel}>
          <div className={styles.prev} onClick={prevText}>&#10094;&#10094;&#10094;</div>
          <div className={styles.next} onClick={nextText}>&#10095;&#10095;&#10095;</div>
          <div><RawText/></div>
          </div>

           </div>
              <Footer/>

                    </div>

                      )
                    }
