import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightBlackTitle from '../../components/rightBlackTitle.js'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import StandardProse from '../../components/standardProse.js'
import Footer from '../../components/footer.js'

export default function Porte() {
  return (
      <div>
          <Head>
            <title>rebecca_ariel_porte ~ portraits_of_some_persons_as_imaginary_cities — new_sinews</title>
            <meta charset="utf-8"/>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="porteBackground"/>

 <CenterGrayTitle><h3>portraits of some persons<br/>as imaginary cities</h3></CenterGrayTitle>
 <RightBlackTitle><h3> ...rebecca ... </h3><h3> ... ariel ... </h3><h3> ... porte ... </h3></RightBlackTitle>

       <Footer/>
             </body>
         </div>
     )
   }
