import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightBlackTitle from '../../components/rightBlackTitle.js'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import StandardProse from '../../components/standardProse.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Porte.module.css'

export default function Porte() {
  return (
      <div>
          <Head>
            <title>rebecca_ariel_porte ~ portraits_of_some_persons_as_imaginary_cities — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="porteBackground"/>

           <CenterGrayTitle><h3>portraits of some persons<br/>as imaginary cities</h3></CenterGrayTitle>
           <RightBlackTitle><h3> ... rebecca ... </h3><h3> ... ariel ... </h3><h3> ... porte ... </h3></RightBlackTitle>

          <p className={styles.storyMarquee}>i.<span className={styles.storyMarqueeInner}>
          <br className={styles.spacer}/>Dry Owlmoy<br className={styles.spacer}/>(For Wolodymyr)
          <br className={styles.spacer}/></span></p>

          <StandardProse>The lights of the Aurora Borealis make their rondeaux each night
          over the long hieroglyph of Dry Owlmoy. If you are quiet enough & the wind is in
          the right place, you can hear the small, emphatic pop (!) of each separate particle
          as it strikes the magnetic field that engulfs the earth like the white of an egg
          engulfs the yolk.
          <br/>
          <br/>
          Although the entire city is a bridge, Dry Owlmoy is like no other bridge
          you have seen. (Perhaps you have dreamed a bridge like this. If so, you
          might attribute it to the involuntary forgeries of the unconscious. Who,
          mssrs. et mmes., is dreaming you?). First there is the Strait. Then,
          there is the city, which straddles it. There is only one road in Dry Owlmoy,
          the road that takes you from the eastern shore to the western shore. But
          the path is not a straight one—its involutions & declivities are so complex
          that, although single, it invariably appears multiple. & yet there is something
          in the measured arcs of its twisting, something that doubles the original
          illusion back on itself so that, having gotten through the scrim of pluralities,
          you find your mouth full of a different gossamer, for the multiplicity resolves
          to a suspicious concord, as if the three classical unities, weary of the House
          of Death, had left it for a more congenial dwelling.
          <br/>
          <br/>
          Dry Owlmoy was built in the future on the bones of a city that will always
          be in the past. This is difficult to explain, so difficult. The city of the
          past was called Owlmoy then, Drowned Owlmoy now. At the base of every pier
          in the new city is a tower of the old one. No one can remember when the last
          of Drowned Owlmoy sank beneath the waters, only that it was always, already
          very long ago. & so the lost city is in Dry Owlmoy & Dry Owlmoy’s in the lost
          city & the archaeologists descend in their moon-blue submersibles & the sunken
          world comes up to meet them. Someday they’ll come back with wonders. (Not yet.)
          The ones they leave behind resign themselves to waiting up a-nights on the abalone
          widows’ walks. When you live in the future, a premonition’s just a crick in your
          neck, boiling the water before you know you want a cup of tea, raking the kelp
          off the roof before it’s landed. When you live in the future, memory is water.
          Water is for drowning.
          <br/>
          <br/>
          Transistor radios, small enough to fit into a tooth, supply news & weather when
          the devices are flicked on with a subtle undulation of the tongue. The most popular
          station broadcasts a constant stream of current events (which is to say future
          events) & those who listen regularly gossip about you & your descendants as if
          they knew you. In Dry Owlmoy they’re using all the latest technology before it
          exists. Much of it they’ve invented themselves. Besides the moon-blue submersibles
          & the radios, they have perfected a source of sustainable renewable energy,
          a marvelous perpetual motion machine. To their great regret, they have found no
          way to send it back in time. It is this problem really, or variations on it, that
          haunts them dawn to dusk. A sort of <i>mono no aware</i> in reverse.
          <br/>
          <br/>
          Because they know what they know, the Owlmoyish have mastered the arts of light &
          also those of lightness. Swimming is their joy & cinema their obsession. Divers
          carve parabolas through the air, slalom through the shadows the bridge casts on
          the water to divide the new city from the old. They have worked out a way to project
          images against the sky itself so there are frequent collaborations between city &
          firmament, entire ballets choreographed around the predicted colors & motions of
          the Aurora. Of course, the purpose of the bridge is not so grand. It connects the
          eastern shore to the western shore. Travelers pass through it often, provided they
          can persuade the Owlmoyish of their need (of need, the Owlmoyish are eminently
          persuadable). There are no names for the myriad turnings of the single street,
          so people must navigate by monuments or else the stars. They know the pelican &
          the flash of eels in sunlight, carven pediments, solar panels & the cries of geese,
          the color of the wolf whose fur gives its hues to an eclipse. These too are involved
          in what they know. <i>Lux et lacrimae rerum</i>. Light & the tears of things.
          <br/>
          <br/>
          </StandardProse>
          <p className={styles.storyMarquee}>ii.<span className={styles.storyMarqueeInner}>
          <br className={styles.spacer}/>Thingprose<br className={styles.spacer}/>(For Kinton Ford)
          <br className={styles.spacer}/></span></p>
          <StandardProse>
          Founded in that baroque fold of time where the (<i>soi-disant</i> ) Age of Beauty had ended
          & the (<i>soi-disant</i> ) Age of Reason had not yet arrived, the great metropolis of
          Thingprose began as an experiment: its entire aim to reconcile in itself the best
          qualities of its absent parents, one of whom it would know only in recall, though
          the other was rushing, rushing through the hazy webs of futurity to meet its progeny.
          (Again, the child would outlive the parent but all that came later.) Because it was
          riddled with secrets, the city was beautiful. Because the secrets bred curiosity, the
          city was reasonable. But to say this is to say little, for although these things are true,
          they are not complete.
          <br/>
          <br/>
          Firstly, you must understand that the city is what it is because of time. That is,
          all cities are what they are because of time but Thingprose is deliberately itself
          because of time. Unlike other slapdash cities, hastily stretching tendrils into the wild
          around a convenient water source or next to a luscious vein of jasper & iron until
          the emergent creatures have developed roads & right angles & opera houses & bureacrats,
          Thingprose had been saved up in the imaginations of its eventual architects, saved up
          like a bulb in the Doomsday Vault. The bulb had been passed down from generation to generation,
          the blueprints drawn, redrawn, endlessly simplified & elaborated until a time when
          the cusp between two ages might crumble, crumble just enough to open a tiny vacuum, a pocket
          of time-beyond-time in which a city might germinate, a city & a mystery. For if you favor
          reason, you’ll call the city a calculator; if beauty, a puzzle.
          <br/>
          <br/>
          Whatever you call it, it cannot be denied that there are two kinds of people in Thingprose,
          the Enigmatics who build, maintain, & refine the puzzle or calculator & the Lucidians intent
          on the exposure of its mechanisms, solution & (in some cases) dissolution. No one really
          knows who in the city belongs to each tribe; the highest law forbids the citizens to declare
          their allegiance openly. In the uncertain climate, the solace of most Prosaics—whether
          Enigmatics or Lucidians—lies in daily examination of their own dedication to the cause &
          valiant guesses about the inner lives of friends & former lovers based on the imperfect
          evidence of gesture. (Guessing is always more fun than knowing.) Of the first level of
          conspiracy, you might say it makes for an atmosphere of suspicion or distrust—you would not
          be wrong. Of the second level (& the levels are ∞), you could not say this if you hoped
          to be fair, for at this level the conspiracy is radically communitarian in its insistence
          that the game is necessary & human & if it all were to stop this instant no one would be
          having any fun at all.
          <br/>
          <br/>
          In Thingprose they will never tell you all their hearts. They will show you the shade
          the red mountain casts on the terraced gardens & ask if you know the thing itself by
          the shape it makes on the lime trees. You will notice that the plumerias form a cipher
          in what seems to be Linear A. There are curated exhibitions of smiling, sighing, weeping,
          & screaming. Gatherings in coffeehouses & salons speculate on the ethics & metaphysics
          of the puzzle. The students of epistemology go masked; their theories of knowledge
          inevitably betray a Lucidian or an Enigmatical bent & if they wish to be truthful,
          they must not risk exposing their identities. Unless, of course, this too is part of
          the game. Braver ones simply tear through the city on the trail of an obscure hunch:
          a new code word spreading virally among the youth, a blank metal card dropped anonymously
          in the mailbox.
          <br/>
          <br/>
          Rooftop soccer is a popular pastime. Theater is another, particularly a subgenre of tragedy
          that deals entirely with the predicaments of people who make all the correct decisions in
          light of the information given them & fail their object anyway because the information is
          never sufficient to the exercise of free will. They never know, never even suspect what
          kind of story they’re in. In these dramas everyone suffers because everyone’s right.
          They’re called secret plays when they’re called anything. It’s always a full house.
          <br/>
          <br/>
          Sandstone, limestone, tile, & slate, the city is scaled in red, white, gray, black,
          green. From above, it looks just like a great fish curled around the base of Mount Lilimaw.
          The ingenuity of the Enigmatics lives up to its reputation. Small puzzles, clues, of course,
          to the whole, lie scattered throughout the city. Lucidians have seen patterns in the geography
          of the nine districts, the secret passages into the undercliff, the hieratic symbols carved
          in the friezes above certain doors. Because it is riddled with secrets, the city is beautiful.
          Because the secrets breed curiosity, the city is reasonable. It is what it is because of time.
          Vertical chessboards with sliding magnetic pieces are built into the walls of an inn near
          the quarry. Left to their own devices, the pieces will begin to move of their own accord.
          <br/>
          <br/>
          </StandardProse>
          <p className={styles.storyMarquee}>iii.<span className={styles.storyMarqueeInner}>
          <br className={styles.spacer}/>Chalient<br className={styles.spacer}/>(For A.P.)
          <br className={styles.spacer}/></span></p>
          <StandardProse>
          In Chalient, the genius of the place unfurls from the setting, this being a hilly
          heath or prairie covered in coarse, long-jointed grasses & gorse. When the wind
          moves through the flora with particular force, the play of motion is like skin
          over the incomprehensible muscles of a vast, humped animal. Where the plants touch,
          there is a steady soughing, as if the animal were breathing.
          <br/>
          <br/>
          The influence of a large lake, invisible from the city walls, but impressed upon
          the awareness of the observer like a person in the next room of a house—that is,
          perceptible in the effects of certain muffled sounds & that prickling awareness
          of adjacent life which all living things possess in degree if not always in
          kind—foments all flavors of rain. Virtuoso storms with lightning & all the fixings,
          diaphanous mists rent by prismatic <i>fata morgana</i>, regular tear-shaped raindrops
          so sturdy & canonically molded it surprises you when they break apart at the nadir
          of their descent. “Precipitate variety” is the running joke & not merely in
          matters of atmosphere.
          <br/>
          <br/>
          Of the people born to Chalient—& the same applies to the ones who choose it—you
          could never say they were indifferent to weather. In the piazza at the center of
          the town, a large ceramic screen covered in delicate waterproof chalks details
          the sort of rainfall for the day, the week, & the month. As yet, the Chalienti
          have observed 10,478 kinds of rain & great excitement & debate always accompanies
          the discernment of a new variety. It is this cultural obsession with detail that
          is their blessing & their curse. When the sun shines, they are grateful; they are
          just as grateful when it doesn’t, for it only ever plays the one song. The highest
          social values are tact & the appropriate use of cinnamon at dinner parties. The
          highest spiritual values are clarity, contemplation, & euphony. Brief fits of
          kleptomania overtake large segments of the population at intervals &, as a result,
          the Chalienti are rather cavalier in matters of madness & property alike. Everything
          changes hands. Object constancy is reserved for books & people.
          <br/>
          <br/>
          Built of light, ceramic brick culled from the clayey banks of the nearby lake,
          the city glows with every shade of near-white from clearest ivory to raw cream
          to a matte intimation of amber. At night, the streetlamps coax translucent shadows
          from the gables of the houses. The view from the top of the Ylassa, a slender
          observation tower lit by a single central oculus, is well worth the climb; & yet
          it is not nearly so impressive as the other singular quality of the place. From
          that small, bare room it is possible to hear a whisper directed towards it from
          any point on the perimeter wall. The physics, to say the least, are daunting.
          There is, of course, a charming local legend involving rain-crossed passions
          but no one can swear to the truth of it.
          <br/>
          <br/>
          The great Archives of Chalient are more like the bazaars & marketplaces of other
          cities, generous halls filled with the hushed commerce of the book-traders & covert
          looks & gestures flung from arcade to arcade. For the Archives are not merely
          the place you go to search out a book, they are also the place you go to flirt,
          fight, & play at politics. Lest you should fear for the books, you ought to know
          that paper’s fate in Chalient is, in any case, short & ignominious; in the damp of
          the city it molds or rots with indecent speed. To this problem, the first librarians
          of Chalient turned their hands. After a time, they emerged from their laboratories
          with a solution—a ceramic paper derived from the same clays as the brick of
          the city—feathery, flexible, & impervious to the elements. & it is to this marvelous
          stuff that all paper texts that reach the city are transferred by the civic scribes.
          Its only bane is gravity, for a book, once dropped, might shatter into a billion
          fragments. Thus, attached to the Archives, an institution known as the Mendery,
          devoted entirely to the recovery of lost volumes.
          <br/>
          <br/>
          Tomcats & young deer roam the street incuriously. They are considered a great nuisance.
          You have never seen so many artisanal umbrellas. You have never walked beneath so many
          pollarded trees.
          <br/>
          <br/>
          </StandardProse>
          <p className={styles.storyMarquee}>iv.<span className={styles.storyMarqueeInner}>
          <br className={styles.spacer}/>Nebligerwald<br className={styles.spacer}/>(For B.A.W.)
          <br className={styles.spacer}/></span></p>
          <StandardProse>
          At last, traveler, in your wandering of some misty coast, you may happen upon the city
          called Nebligerwald, which cannot be reached by deliberation any more than an earthquake
          can be reversed or love compelled. Stumbled onto, chanced upon, startled into existence,
          this Nebligerwald, but never otherwise: those who seek it will never find it & those who
          find it will never leave it, properly speaking. For always—even if they should depart its
          encircling boundary of fog, curled & whorled like the hides & horns of Angora goats—always
          will they carry with them certain marks of their sojourn there, more or less legible
          depending on their moods & general condition. These signs may be as subtle as a mild
          wilderness about the eyebrows, a laugh that echoes a moment longer than acoustics should
          really allow, myopia, a persistent parapraxis in matters of quotidian record, & a penchant
          for paronomasiac play. Signs subtle—but also signs pronounced—a dwelling in the ironies,
          the liberal exercise of flirtation, flattery, & stubbornness without limit, an obsessive
          care for the technical, historical, & social details of various appetites & their satiations,
          & a tendency to hold grudges equaled only by a talent for the kind of loyalty whose generosity
          is so holy-fool profound that in order to bear it, those who learn of it (including the
          talented themselves) must contrive to find this capacity faintly, sweetly risible. The most
          obvious sign of a Nebligerwalder is also the rarest: an omnipresent wisp of roric iridescence
          smelling faintly of vetiver that issues—ever, always—like ambergris atop the spout of the
          world’s smallest whale, from the left ear. In Nebligerwald, they do not quarrel with the
          proposition that the art of losing isn’t hard to master. Rather, understanding the irony of
          the phrase, they add a codicil to render it explicit: the art of losing isn’t hard to
          master—except that mastery of this art is, in fact, a life’s work.
          <br/>
          <br/>
          Nebligerwald is coastal but belongs to no particular coast; sometimes it has been known
          to appear on islands or peninsulas, estuaries or coves, more rarely in the midst of some
          landlocked forest fed by the commingling of many rivers. Although it is—& remains—a place
          of no fixed address, certain combinations of landscape seem to create the conditions for
          its manifestation more perfectly than others: a concentration of proximate microclimates,
          topographies dense with ten-thousand shades of green, hills soft with moss & carelessly
          rumpled like the plush creases of an unmade bed, & water, water, above all, a preponderance
          of water.
          <br/>
          <br/>
          This last element has suggested to scholars the sustaining requirement for the city’s famous
          shroud, its walls of mist, which, unlike the cloak of invisibility said to have shielded
          the Son of Lír, seems to be material rather than magical in nature. The fogs of Nebligerwald
          produce an optical illusion analogous to the Brockenspectre of the Harz Mountains or the
          Dark Watchers of the Santa Lucia range, though the effects are as much comic as forbidding:
          a spectral panorama of stock players, much like the figures of Commedia dell’Arte, who act
          out mysterious scenes in pantomime. They are called, by the citizens of the place,
          the <i>Bittersüße Geister</i>.
          <br/>
          <br/>
          Some have claimed that the choreographies of these dear ghosts narrate the histories &
          founding myths of the city, while others have seen in their antics a comic revisioning of
          how the city could have been or might still be in some possible future. Another school of
          thought understands these indeterminate phenomena as condensations of the daily life of
          the city streets, reflecting in partial shadow a meeting of old friends, a wallet dropped
          & returned, a lively debate in the central forum, a funeral, a quarrel, a dance; in short,
          according to this theory, these shadowy creatures are, in effect, the dreams of the city.
          It is the <i>Bittersüße Geister</i> who will know you when you arrive & draw back the heavy folds
          of fog to let you in.
          <br/>
          <br/>
          Those who have been to Nebligerwald have compared it to a Mitteleuropean spa town hybridized
          with a model city planned for residence on the moon. (Baden-Baden & utopian science fiction
          are frequently invoked as points of reference.) A combination of Bauhaus, <i>Jugendstil</i>,
          & Metabolist styles of architecture & furnishing predominate, punctuated by buildings & bridges
          whose organic forms, almost representative of birds or copses of trees or geese hatching from
          barnacles, recall the designs of Gehry & Calatrava. Bicycle, kayak, & train are the preferred
          modes of locomotion & the occasional houseboat studs the quieter waterways. The liveliest
          nexuses of the city bloom at the four points of the compass & at its center: the public
          university with its suite of libraries (north), the great baths where springs, hot & cold,
          rise up from some cryptic aquifer (south), the theater district (east), the forum (west),
          & (center) a small mountain about which there are many picturesque local legends—& not a
          few concerning a seemingly immortal pig called Cockaigne who can be seen rooting placidly
          near the greenhouses at the base of the peak.
          <br/>
          <br/>
          More fierce & more inexorable far than empty tigers or the roaring sea, a strange, oily
          wildfire burns like a furnace on the mountain’s southern slope, sends up its smoke forever (?),
          hot & indelible & indecipherable as the blazes of Centralia. Of this, the citizens rarely speak,
          though all who have achieved the age of reason are required to sign up for regular shifts to
          monitor the blaze, which seems to contain itself by some interior principle of flame, though
          sometimes it forgets itself & grows or diminishes accordingly. & so the Nebligerwalders watch
          & wait, interfering only by vigilance. Never have I seen a face so implacable as that of
          a firewatcher on the cusp of dawn in Nebligerwald—& never do I hope to again.
          <br/>
          <br/>
          At the top of the mountain are two pairs of coin-operated binoculars that accept the tribute
          of a fern or a violet or a flat pebble in place of currency (at present, the economic
          experiment in Nebligerwald has a decidedly Marxist inflection). The binoculars are convenient
          both to the labyrinth of hiking paths that wend through the declivities of the mountain & the
          funicular railway with its antique, brass fittings. The view from the first set of binoculars
          inevitably resurrects a memory you were not aware of possessing; the view from the second
          depicts vivid scenes drawn from your counterfactual lives. These devices are employed
          exclusively by tourists; Nebligerwalders find them detrimental to the maintenance of viable
          ratios of levity to gravity. They prefer to send one another urgent missives in glass capsules
          by way of the tangle of pneumatic tubes that permeates the infrastructure of the city as
          similar structures linked the Grand Hotels & the post offices of nineteenth-century Paris.
          <br/>
          <br/>
          A languid chain of gardens—pleasure, perfume, & practical use—weaves through & around & back
          on itself, everywhere, everywhere, everywhere. Lit by painted paper lamps & enormous,
          verdigris lanterns, the green corridors of the city tremble with silhouette & fountain,
          the vibrations of chamber pop, the whir of well-tuned velocipedes, the quiet plash of oar
          in water or quick conversation. Tourists in Nebligerwald may, occasionally, be troubled
          by the prescriptive bent of the culture, which thrives on arcane language games, complex
          codes of etiquette, often impenetrable to outsiders: philosophy, local wit, praise, &
          censure are among the garden-variety modes. Certain inflexibilities of schedule also
          typify the life of the city: early to bed, early to rise.
          <br/>
          <br/>
          Nonetheless, Nebligerwald is prepared to indulge the ones who find their way to it,
          urbane in its urbanity; it operates by strict Laws of Abode & the welcome of the stranger
          among them. In the night markets of summer, you have but to ask to know or to taste or to
          listen or to speak or to feel or to sense or to sway & in this you shall be answered.
          The city is known for its rich & varied cuisine: cafés & dim sum palaces, taco carts
          & hand-pulled noodles, blini & craft cocktails, & a haunting local spice procured by
          smoking the bark of a species of lotus local to the city & nowhere else. Fresh produce
          & impeccably roasted coffee are abundant. Fair labor practices & artisanal fanaticism
          are de rigeur. It is impossible, there, to eat a bad meal or drink a poorly brewed cup.
          <br/>
          <br/>
          A plague of forgetting lies dormant in the springs that feed the great baths (though
          of this, as of the fire on the mountain, they do not often speak). At irregular intervals,
          it shakes itself to life like an invisible beast, turns the waters to Lethe, & all who
          cleanse themselves in the ornate frigidariums, tepdiariums, & caldariums, who swim in
          the canals or drink from the taps, find themselves, for a period of approximately three days,
          unable to generate new memories. To these random oubliettes in their personal histories—&
          in the history of their city—the Nebligerwalders are reluctantly resigned—can sometimes
          even laugh at their collective amnesia or argue with all their considerable intellectual
          passion about whether the communal nature of the virus makes it easier or harder to bear.
          <br/>
          <br/>
          On these rare, elided nights—<i>sous rature</i>—when the city obscures itself in the fist of
          the temporary plague & the <i>Bittersüße Geister</i> pace their lanes of mist in restless
          agitation—on these nights—if you take no drop of intoxicating water, stay waking through
          the darkling hours, you will observe copies of the <i>Odyssey</i> that read themselves backwards
          by their own light, songs of some invisible collective (dyeing all the air the color of
          a longed-for name), pervasive intimates inventing the rhythms of their converse as if
          they had been the first to discover the pleasure of repetition & variance, dancers
          partnered with hamadryad birch or shadow of a little god or fairy, owls declaiming
          their latest poems, children speaking future to their parents & their unknown selves,
          a man—just there—conversing with a statue-come-to-life, man too rapt in miracle of
          conversation to notice that he ceaseless, ceaseless weeps a stream of phosphorescent
          tears—as if—on this—a night that has no memory—there were no labor, love or sorrow in
          the world, only time & wonder, there, & music—
          <br/>
          <br/>
          <br/>
          <br/>
          </StandardProse>

       <Footer/>
             </body>
         </div>
     )
   }
