import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import CenterGrayTitle from '../../components/CenterGrayTitle.js'
import CenterBlackTitle from '../../components/CenterBlackTitle.js'
import StandardProse from '../../components/standardProse.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/EssayMode.module.css'

export default function SalutingAHex() {
  return (
      <div className={styles.container}>
          <Head>
            <title>saluting a hex of gangrenous sky_or: Brandon Shimoda's ritual inversions — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header/>

       <CenterGrayTitle><h3>saluting a hex of gangrenous sky</h3></CenterGrayTitle>
       <CenterBlackTitle><h3>or: Brandon Shimdoa's ritual inversions</h3></CenterBlackTitle>

       <p className={styles.authorItalic}>—Steve Barbaro</p>

       <br/>
       <br/>
       <StandardProse>
       The scale of any given memorial, the air of the thing, the breadth and the build
       and the torque—should not the whole deal be jigged to the pitch of the absences it
       would re-conjure? Brandon Shimoda’s <cite> The Grave on The Wall </cite> (2019, City
       Lights Books) knows a thing or clairvoyant two about the functional dysfunctions of
       commemorative monuments. An ancestral memoir fluttering with airy exactitude between
       spells of dream-journal and travelogue, self-appraising photo-compendium and documentary
       testament to the obfuscation of the facts of Japanese-American incarceration during
       the second World War, <cite> The Grave on The Wall </cite> is also a kind of dirge
       lamenting the broader dirge-scape.
       <br/>
       <br/>
       Case in point: the giantly-statured Peace Statue of Nagasaki’s Peace Park comes under
       the memoir’s scrutiny, what with the sculpture’s “mute, immobile, not human” disposition
       seeming more an enshrinement of the atomic bomb than its victims. Ditto for the way
       Shimoda’s scrupulous eye is later aimed at the “unclear” World Trade Center national
       memorial. The contraption of recollection inspired by the most imagination-snagging
       recent disaster to transpire upon U.S. soil sports mechanized water flowing snake- and
       smoke-like across walls and down into holes. Yet despite the hastily-canonized mid-empire
       memorial’s capacity to produce an ever-ready “overabundance of dispassionate eyes,” the
       setting remains “too conceptual to satisfy the patriotism stirred by—and maintained
       since—September 11, 2001.” And meanwhile mere blocks from the twin towers’ former abode
       there stands lower Manhattan’s largely-infrequented African Burial Ground National Monument.
       A memorial to a largely built-over cemetery itself allocated 300-plus-some years ago for
       the often involuntarily-relocated members of the African diaspora inhabiting early New
       York City, the African Burial Ground seems so overwhelmed by the fortifications of the selfsame
       forces of Capital that once upon a time fueled the Atlantic slave trade, “the form of the
       surrounding buildings with their thousands of windows” behind which loom “the people who
       manufacture the blood of their businesses” as to appear “fugitive, because it feels like
       you are being surveilled, tabulated.”
       <br/>
       <br/>
       As <cite> The Grave on The Wall </cite> accumulatively diffuses, shrine beyond shrine,
       history-corralling-history, the insufficiencies of civic memory congeal and overlap with
       the span and inconspicuous spin of the strata comprising the sun-orbiting earth. The
       terrain of bygone truth is a byway of loss-echeloned voice. So it makes a kind of cosmic
       sense that the narrator duly comes to imagine, with apt geological logic, the uppermost
       aspect of the earth itself serving as a ready medium by which to amplify mortality’s centrality:
       <br/>
       <br/>
       <blockquote className={styles.boldQuote}>
       If we marked every death—not even yet a grave—with a mound, the earth would be covered in mounds.
       The mounds would act as impassive prophecy, to which the living grow accustomed, in understanding
       their bodies, their destinies, death, in general, as being part of the evolving topography of earth.
       </blockquote>
       <br/>
       <br/>
       In this way, at least, the history of breath would achieve some less incommensurate equilibrium
       with the history of the planet. The solution at hand is not fanciful so much as lucidly drastic.
       Aggregate, urgent. Aggressively non-transient. The structures necessary for a truer (see: calamity-
       precluding) attunement with the past simply seem beyond current imaginative capacities. Yet if
       the cooly relentless laments for the failures of communal memory in The Grave on The Wall—itself
       the first non-poem-predominating book in Brandon Shimoda’s opus—are in no small part the fruit of
       Shimoda’s unusually hyper-un-myopic sense of scale, such scale is a constant in his oeuvre.
       <br/>
       <br/>
       <p className={styles.standardProseSectionBreak}>{` —  —  —  —  —  — `}</p>
       <br/>
       <br/>
       The space of Shimoda’s 2011 poetry collection <cite> O Bon </cite> (Litmus Press) is a
       calamitously verdant space of “celebration/ incised/ onto terracing air” (“Through the Ghost
       Fires.”) If the overriding structural orientation of our epoch is so operatively brutal
       as to erase memory and make a self-serving staircase of the very earth, <cite> O Bon </cite>
       flutters up and down the smug rungs of the all-pervasive underworld at the incantatory
       expense of the chaos.
       <br/>
       <br/>
       The milieu of the poems of <cite> O Bon </cite> is such that “A lady inside/ a translucent
       turnip” and “Beets and radishes chirping” both alike cohabitate with “gummy, embryonic
       skulls/ and bomb shadows” (“Lake M”). Ends of things seem so inextricably tied to beginnings
       as to render the formalities of modern civic memorials intrinsically aloof, almost snobbish.
       “The tastelessness of flesh” rests “upon a ravaged tongue” whereon also sits “the taste/ of
       flesh to an eroding brain” which at once “buds on a ravaged tongue” (“The Inland Sea”). And
       while nuclear weapons and their fallout are persistently referenced yet never quite granted
       definitive procreant credit, the all-but-end-stop-less poems of <cite> O Bon </cite> would
       reverse history’s horrid course and allow the now “darkened shore” onto which our ocean-ancestors
       once upon a time migrated to serve as a stage where “ribbon integuments freshen/ into antiquity”
       (“Crucian Carp”).
       <br/>
       <br/>
       In the face of all the ritual-amidst-chaos, <cite> O Bon</cite>’s cooly drastic honorific
       correctives seem ideally embodied by one particular character: the former-priest-turned-cannibal-
       narrator of “The Corpse Eater.” Amidst teasingly tactile ruins and strontium-suffused strata,
       The Corpse Eater’s supra-sonic orientation represents indeed the very opposite of capitulation.
       “Plunging the opened body/ eloping/ in fallout/ between tree between tree,” the narrator consummates
       a full-bodied fling with fatality in the middle of valleys whose regenerative expansiveness
       “bruises the raining of ears/ becoming foliage.” The transposed torque of mid-madness life is
       in fact such that “the dead waste dead return.” The tongue waves and flutters, as if the
       instrument of speech is here merely the teeth’s deputy. “I hear you tell/ I want to hear you
       tell,” The Corpse eater nonetheless sings with cumulative sensorial attunement, in response
       to the soil-broaching vivacity of the supposedly posthumous:
       <pre className={styles.quotedPoemLineation}>{`
         beneath flapping roots the will to part
          the ground to say
               I hear you tell
  I want to hear you tell
          mandibles masting
           your throat
          in slats
         `}</pre>
       Bonding the extant with the extinct, The Corpse Eater’s embrace of loss builds new byways
       between speech and the unspeakable. “I flay the form for your return,” The Corpse Eater
       ensures, righteously hastening existential cycles. And the bridge between breath and non-breath
       becomes so mellifluously navigable as to cascade down the page with the capsized sacramentality
       of the flags at the poem’s beginning descending—like a kind of anticipatory corrective of
       the snake-like national memorial water flowing lamentably aloofly through <cite> The Grave on
       The Wall</cite>’s very framework—into oblivious corpuses of liquid.
       <br/>
       <br/>
       <p className={styles.standardProseSectionBreak}>{` —  —  —  —  —  — `}</p>
       <br/>
       <br/>
       As intrinsically remote from would-be encapsulating scrutiny as canonical modern memorials
       are from the full-bodied labor of genuine memory—such might be an accurate summation of
       Brandon Shimoda’s post-<cite>O Bon </cite> books of poetry. Each of these collections simply
       cultivates its own unfailingly uncompromising sort of over-archingly elusive ritual space.
       <cite> The Girl Without Arms </cite>(2011, Black Ocean) is a sprawling end-stop-less
       collection of such reverberating sensorial twirl and pace as to render its narrator
       a kind of self-sieving deity, spying the venerable everywhere yet never not shirking
       subsuming fealties. Chaos preponderates, “THE AIR THAT STUNS PREDICTS,” and yet reason
       and vision—and perhaps most essentially, memory—remain salvageable enough to birth
       the desire that “we have to do something/ We have to refuse to suffer an ending.”
       <cite> Portuguese </cite>(2014, Octopus Books) exudes the intimately hyper-sociable
       luminosity of a kind of self-effacing jubilee. “When stuffing slipper into your mouths,”
       one of the many poems titled “For The People” instructs with the kind of casual cosmic
       bent indicative of a more general galactic bearing, “Beware of what makes you extraterrestrial.”
       The words of <cite> Evening Oracle </cite>(2015, Letter Machine Editions) oft-appear to be
       operating at the very frontiers of their inherent materiality. Even fuzziness is immense.
       Accents and registers cooly cohabitate as if ceremonially. “One dreams of living above a
       bathhouse/ In a snow-covered field/ With a procession of white animals/ Passing
       nightly (‘Tsurunoyu’).” Immensities themselves become fuzzy. And the overt-ness of <cite> Evening
       Oracle</cite>‘s polyphony—certainly present in Shimoda’s previous collections, but here bloomed
       into a novelly voluminous stratigraphy—seems to birth a fluidity of utterance all the more
       sonically singular for being operatively suspicious of self-limiting singularity.
       <br/>
       <br/>
       <p className={styles.standardProseSectionBreak}>{` —  —  —  —  —  — `}</p>
       <br/>
       <br/>
       Then in time there is a refrain-like recourse to a landscape of illuminating extremity. At
       once robust and free, rigorous yet airy, <cite> The Desert </cite>(2018, Song Cave) exhibits
       an uncommonly rangey formal fluidity. Continuing in <cite> Evening Oracle</cite>’s spirit
       of nature-mimicking miscellany, <cite> The Desert </cite>treats us not only to poems but
       also journal entries, diffusively-unnamed sectioned-lyrics, email excerpts, and even
       photographical-hints of the kind that later serve <cite> The Grave on The Wall </cite> so
       vibrantly.
       <br/>
       <br/>
       Amidst the film-turned-poem’s unfolding however, one thing is certain: the narrator’s voice
       roves with weirdly centering élan, at times weirdly personal—musing upon a nephew’s mid-bathroom-
       habit facial expressions, say—and at times studied, such as when Dr. Bhrigupati Singh is
       invoked to provide geo-philosophical contextualization. But if even, as Nao writes at the 1:30
       mark, “the small organic gestures of life emulate the various efforts of modernization,” is
       not the natural world fated for uniform exploitation?
       <br/>
       <br/>
       “Most sheep devote their lives to be de-skinned, to be de-wooled,” Nao states as the
       movie-mirroring poem-sequence approaches its own conclusion. “What is the purpose of a human’s
       existence? If not to be breathing on earth, our soul deskinned, de-wooled for ontological
       certainties?” But as the film is all the while being ekphrastically peeled and peeled, it
       becomes apparent that the systematic nature of Nao’s own ordering principle would, with
       signature dexterity, subsume the very sort of interspecies power that the narrative is
       all the while critiquing.
      <br/>
      <br/>
       The wont to simply break down a motion picture into its constituent parts—to return,
       that is to say, a kinesis-dense, stock unit of modern life such as a film to its frame-by-frame
       units of stasis—is itself a fruitfully intrusive stratagem granted extra vigor via the assiduousness
       of Nao’s attention. But if the overarching reality of early 21st century modernity is such
       that protracted attention itself seems exotic if not luxurious, <cite>Sheep Machine</cite>’s dispersed
       thematics also seem a subversion of the entrapment-conducive fixity of prolonged attention.
       Perhaps the reality ensnaring us—an overarching reality of our own making, legitimized anew
       each day by the cynical acts to which we accede and accede—is ripe for an ameliorating
       flux via our own rejigged will. “I have nothing to say to things,” Vi Khi Nao insists,
       elucidating a frontier in an otherwise brink-breaching oeuvre, “that appear to be not changing."
       </StandardProse>


    <Footer/>
          </body>
      </div>
  )
}
