import Head from 'next/head'
import Link from 'next/link'
import CenterBlackTitle from '../../components/centerBlackTitle.js'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/TombModel.module.css'

export default function TombModelCover() {
  return (
      <div>
          <Head>
            <title>brandon_shimoda ~ excerpts_from_TOMB_MODEL_OF_A_NOBEL'S_HOUSE — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="tombBackground"/>
       <br/><br/><br/><br/><br/>
       <CenterBlackTitle><h3> :: excerpts<br/>from _tomb_<br/>_model_of_a_<br/>_noble's_house_ :: </h3></CenterBlackTitle>
       <br/><br/>
       <CenterGrayTitle><h2> :: brandon<br/>shimoda :: </h2></CenterGrayTitle>
       <br/><br/>
       <CenterBlackTitle><h3><span className={styles.arrows}> ➜ ➜ </span><span
       className={styles.link}>place is our new<br/>destitute imperative</span></h3></CenterBlackTitle>
       <br/><br/>
       <CenterBlackTitle><h3><span className={styles.arrows}> ➜ ➜ </span><span
       className={styles.link}>we need to find<br/>the right geography<br/>for
       our revelations</span></h3></CenterBlackTitle>
       <br/><br/>
       <CenterBlackTitle><h3><span className={styles.arrows}> ➜ ➜ </span><span
       className={styles.link}>don't forget that for<br/>now it's strawberry season.<br/>yes.
       </span></h3></CenterBlackTitle>
       <br/><br/>
       <CenterBlackTitle><h3><span className={styles.arrows}> ➜ ➜ </span><span
       className={styles.link}>i still have no way to<br/>survive but to keep
      writing<br/>one line, one more line, one<br/>more line...
       </span></h3></CenterBlackTitle>

       <Footer/>

       </body>

       </div>

    )
 }
