import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../../components/header.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Zamora.module.css'
import React, {useState} from 'react'
import { images } from '../../GalleryData/ZamoraCarouselData'


export default function Zamora() {
    const [currImg, setCurrImg] = useState(0);
    function prevImage() {
       if (currImg > 0) {
      setCurrImg(currImg - 1);
     }
    }

    function nextImage() {
      if (currImg < 7) {
      setCurrImg(currImg + 1);
     }
    }
return (
    <div>
        <Head>
          <title>felicia_zamora ~ selections_from_'quotient' — new_sinews</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/images/favicon.ico" />
          <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
        </Head>

        <Header headerBackground="zamoraBackground"/>

        <div className={styles.container}>

        <div className={styles.carousel}>
        <div className={styles.prev} onClick={prevImage}>&#10094;&#10094;&#10094;</div>
        <div className={styles.next} onClick={nextImage}>&#10095;&#10095;&#10095;</div>
        <Image src={`/images/Zamora${currImg}.png`} width={1050} height={500}
        className={styles.imagery} alt="Two Eyes in One Eye: A Delirium"/>
        </div>

         </div>

        <Footer/>

              </div>

                )
              }
