import Head from 'next/head'
import '/styles/globals.css'

function MyApp({ Component, pageProps, title}) {
  return (
    <>
  <Head>
    <title>{`${title} — new_sinews`}</title>
    <meta name="description" content="Generated by create next app" />
    <meta charSet="utf-8" />
    <link rel="icon" href="/images/favicon.ico" />
  </Head>
  <Component {...pageProps} />
  </>
 );
}

export default MyApp
