import Head from 'next/head'
import '/styles/globals.css'

function MyApp({ Component, pageProps}) {
  return (
    <>
  <Head>
    <title>{Component.title}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charSet="utf-8" />
    <link rel="icon" href="/images/favicon.ico" />
    <Html lang="en">

  </Head>
  <Component {...pageProps} />
  </>
 );
}

export default MyApp
