import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
      </Head>

      <body>
        <section className={styles.top}>
          <div className={styles.iconPlusSitebar}>
          <a href="https://newnewsinews.com"></a>
          <nav className={styles.siteNav}>
            <button>issue_4</button>
            <button>issue_3</button>
            <button>issue_2</button>
            <button>issue_1</button>
            <button>new sinews</button>
            <Link href="/about"><button>about</button></Link>
            </nav>
          </div>
            <pre className={styles.graffiti}>
                 new sinews             new
              sinews     new sin        sin

              new sinews new sinews  

             eww         news      new      
              sinews new   sinews    new    
              sinews sinews new new  sin
            new sinews
          </pre>
            </section>

            <section className={styles.middle}>
            <pre>

      <span className={styles.lightTypeface}>new sinews</span>

      <span className={styles.darkTypeface}>late empire new writing</span>

      <span className={styles.lightTypeface}>issue four</span>

      <span className={styles.darkTypeface}>featuring</span>

      <span className={styles.lightTypeface}>brandon shimoda

      k-ming chang

      evan isoline

      christa romanosky

      gabriel palacios

      allison hummel

      mike corrao

      vi khi nao

      grant maierhofer
       </span>
      <span className={styles.darkTypefaceSpecial}>now showing</span>
      </pre>

              </section>
              <section className={styles.bottom}>
                </section>

                <footer className={styles.socialLinkFooter}>
      <a className={styles.socialLinkTag} href="https://www.twitter.com/new_sinews">twitter</a>
                  </footer>

                </body>

    </div>
  )
}
