import Head from 'next/head'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import CenterBlackTitle from '../../components/centerBlackTitle.js'
import StandardProse from '../../components/standardProse.js'
import GalleryLineation from '../../components/galleryLineation.js'
import styles from '../../styles/TwoEyesInOne.module.css'


export default function TwoEyesRawText() {
  return (
      <div>
          <Head>
            <title>vi khi nao ~ two_eyes_in_one_eye_raw_text — new_sinews</title>
            <meta charset="utf-8"/>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>
        <br/>
        <br/>
        <CenterBlackTitle><span className={styles.grayShadow}><h3>vi khi nao</h3></span></CenterBlackTitle>
        <br/><br/>
        <CenterGrayTitle><span className={styles.blackShadow}><h3>two<br/>eyes in one<br/>eye: a delirium</h3></span></CenterGrayTitle>
        <br/><br/>
        <CenterGrayTitle><span className={styles.blackShadow}><h3>version<br/>one: two eyes in one<br/>eye</h3></span></CenterGrayTitle>
        <br/><br/><br/><br/><br/><br/>
       <GalleryLineation content= {`
The bird is walking around the courtyard      

                                                                  looking for a religion with a pair of oculi.
                                                                  Comparing itself to the cathedral. Landscape greets their
                                                                  bodies. Bird and cathedral share contorted & arched
                                                                  postures. The bird bent by fata morgana gazes at
                                                                  the light /// the light is eating into one another. Eating
                                                                  into each other’s time. The father of the moment eats
                                                                  eats eats into [    ]. It blinks—in no [      ]—
                                                                  metamorphoses into a cathedral. The bird opens wide its
                                                                  buttresses, spreading its congregation of feathers. 
        `}/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

        <GalleryLineation content= {`
  The church opens its white      

                                                                  buttresses. Flock into oblivion. Lusters of
                                                                  awakening open the throat of Our Lady’s chapel. Shove
                                                                  down all the doors. It will make the body hide the bread.
                                                                  The church is going to ask the bread to molest the body. 
                                                                  Spread the legs open and shovel the past into it.
         `}/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <GalleryLineation content= {`
         The heart of the church is cold    

                                                                               & blistery. Ready to be lightwood—splintered
                                                                  by time /// Darkness is gentle and enhances the stomach
                                                                  lining, the ambulatory nave, with wisdom and
                                                                  confidence.
          `}/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <GalleryLineation content= {`
          The congregation walks into the stomach    

                                                                               lining of the bird. Sits down. The professor, a 
                                                                  physicist, opens the bible made of birdseeds. Looks down
                                                                  at her watch. The priest will cut the lives of others with
                                                                  his cryptic voice.
           `}/>
           <br/>
           <br/>
           <br/>
           <br/>
           <br/>
          </body>
      </div>
  )
}
