import Head from 'next/head'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import CenterBlackTitle from '../../components/centerBlackTitle.js'
import StandardProse from '../../components/standardProse.js'
import GalleryLineation from '../../components/galleryLineation.js'
import styles from '../../styles/TwoEyesInOne.module.css'


export default function ZamoraRawText() {

  return (
      <div>
          <Head>
            <title>felicia zamora ~ selection_from_quotient_raw_text — new_sinews</title>
            <meta charset="utf-8"/>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <CenterGrayTitle><span className={styles.blackShadow}>
        <h3>felicia zamora</h3></span></CenterGrayTitle>
        <br/><br/>
        <CenterBlackTitle><span className={styles.grayShadow}>
        <h3>selection from 'quotient'</h3></span></CenterBlackTitle>
        <br/><br/>
       <GalleryLineation> <pre>{`
                        what is still is not
                        contained. & the sallow
                        sees itself as limb, as broad-leaf
                        extension
                        in earth as earth. A delving root
                        stretches inside, burgeons out —
                        anchors to pond’s surface
                        & heaves with rhythms of weather
                        & surface, here, loves restless.
                        Yearns to permeate, to divest.
        `}</pre></GalleryLineation>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <GalleryLineation> <pre>{`
                        Interrobang, a gathering of sorts.
                        Synesthesia evokes before
                        speech lost in its own
                        trembling throat; language mutates
                        with us — ~ITAL pick a number ~ITALI
                        & the card game becomes
                        mathematical. Creation
                        in sequence before — the counters
                        of numbers only count. Quantity
                        allows observance. ~ITAL How do you spell~Ital — ? Observe
         `}</pre></GalleryLineation>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <GalleryLineation> <pre>{`
                        & what forms magic
                        originates as magic. We think
                        in ITAL inventory ITAL to lock universals
                        in brainwaves & tongues. ITAL Ownership ITAL
                        out of word is dangerous. ITAL Forget, ITAL
                        the same. No matter
                        calls forth without action. Words
                        reveal magical elements.
                        A defect of magic:
                        thinking it is magician.
          `}</pre></GalleryLineation>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <GalleryLineation> <pre>{`
                        Numerator thrones double
                        line over line hover, verge —
                        cross hatch
                        the mold, to make
                        figure obey the clay,
                        the design. What division
                        strips. Naked & exposed. The source
                        no longer boon; ear no longer bent
                        in heed. What reveals
                        in the shuck. What visions —
          `}</pre></GalleryLineation>
           <br/>
           <br/>
           <br/>
           <br/>
           <br/>
           <GalleryLineation> <pre>{`
                        How eyelashes & tree branches
                        cast similar shadows — a game
                        of proportions. & when we admit:
                        ITAL My magnitude hides, swallows
                        in this body ITAL — a grave
                        tucks in fissures of hemispheres,
                        mirroring. In the cerebral cortex,
                        we fall into lobes & bones. Sutures
                        of intersection. We count: ITAL one one-thousand,
                        two one-thousand ITAL, under folds, in wait of boom.
           `}</pre></GalleryLineation>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <GalleryLineation> <pre>{`
                        Inverse — tongue
                        a pendulum. Nests of mud
                        sculpt in the lighthouse rafters
                        where we juggle eggs to and fro
                        until the swallows
                        peck our knuckles raw.
                        In the blood, in the shell-
                        scatter, a crime scene
                        to witness: the cold
                        potter’s wheel, spins still.
            `}</pre></GalleryLineation>
             <br/>
             <br/>
             <br/>
             <br/>
             <br/>

            </body>
          </div>
    )
  }
