import Head from 'next/head'
import Header from '../../components/header.js'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import LeftBlackTitle from '../../components/leftBlackTitle.js'
import StandardProse from '../../components/standardProse.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Moss.module.css'

export default function Moss() {
  return (
      <div>
          <Head>
            <title>samuel_moss ~ the_veldt_light — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="mossBackground"/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <pre className={styles.title}><span className={styles.inverseShadow}><span className={styles.t}>{` t`}</span>{`
  h
      e`}<br/><br/>{`ve ld `}<span className={styles.t}>t</span>{`  `}</span> <br/>{`l i gh `}<span
      className={styles.t}>t</span></pre>
      <br/>
      <CenterGrayTitle><h4>... ... <i>samuel</i> ... <br/>... <i>moss</i> ... ...</h4></CenterGrayTitle>
      <br/>
      <br/>
      <br/>
      <LeftBlackTitle><h3><span className={styles.titleShadow}>the veldt-light</span></h3></LeftBlackTitle>
      <StandardProse>
      Of the qualities of the Veldt, that which is most striking is the light itself. I can tolerate it now. Upon first
      coming to the Institute it was utterly overwhelming. It is not uncommon for new patients to stay in their room
      with the blinds drawn for many days, venturing into the outer rooms only with their heads lowered, taking every
      care to keep from facing those great windows.
      <br/>
      <br/>
      The light is itself a healer, or perhaps better said, a teacher. The sun rises every morning in the east and casts
      its rays and long shadows toward the west for an hour or so. Rapidly the sun rises in the sky until it seems to hang
      directly above the Institute—that is to say, in the very center of the veldt itself—at which point all shadows
      diminish to nothing.
      <br/>
      <br/>
      For those of us still attached to the outer world, the presence of a personal shadow is taken as a given. Looking
      at the ground reminds us that we contain mass, that we take up space, that we are ensconced in and constitute a body
      which blocks the sun and projects an isomorphic field of darkness onto any object which passes beneath.
      <br/>
      <br/>
      It is different in the Veldt. When the sun is hanging above the center of the Veldt one steps outside to find no
      shadow beneath them. This phenomenon alone can send a new patient scurrying back to the protective dark of the
      Institute. The absence of a shadow suggests, in no weak terms, that one’s own body has evaporated into
      nothingness, that the single thing one can rely on totally is without form or substance.
      <br/>
      <br/>
      Here, the passage of the sun’s light is considered a miraculous event. This is because for as long as one
      looks at a ray of the sun’s light it never appears to move, yet if one leaves and returns the light is inevitably
      found in a different place.
      <br/>
      <br/>
      Beyond this the veldt-light serves as its own actor. The nuance of the light is manifold, and only with time and
      exposure can a patient come to understand this. The way it arrives through the windows, forms tilted blocks on
      the floor, moves as one unit through the spare, straw-colored rooms of the Institute. One may object to this, call
      it a paradox. For if the light cannot cast shadows how can it be seen in the rooms of the Institute itself? I wish
      I could convey the answers to these questions in a way that could be understood.
      <br/>
      <br/>
      Living in a light like this—for days, weeks, months on end—changes a person, opens up ways of seeing that were
      previously unknown and unknowable. The illumination of the veldt-light is such that nothing can be hidden, neither
      inside nor outside; neither visible nor invisible. For those dark things must live in the shadows, and here there
      are no shadows.
      <br/>
      <br/>
      One finds that the light illuminates each thing <i>as itself in itself</i>. One sees too much here and learns to see
      too much. Looking out at a forest or field under the world-light, one is able to work under the illusion that
      a grouping of things is one object in itself. Under the veldt-light each string of grass can be seen individually
      and for itself. The unilluminated mind is capable of seeing only so many things at once. It is only able to manage
      a mass—like the veldt—by collapsing the multitude into a unified grouping of objects. So, the myriad blades of
      grass appear to be just one veldt. Under this veldt-light one comes to grips with the sheer magnitude of the many
      objects. The mind must conform to the inescapable grouping of the million blades of grass. It is a challenge at
      first, but with some training one finds the task to be possible. The light catalyzes this. This small realization
      changes the mind so that other groupings naturally decompress. One can go on and understand a forest as
      a multitude of individual trees, a building as a multitude of individual bricks, the human race as no single
      object.
      <br/>
      <br/>
      I eventually arrived at a point where the light no longer repulsed me. It was then that I came to find that there
      exist various veldt-lights, each of which differs in its characteristics. The morning light is flighty and
      untrustworthy. It illuminates objects by its own vicissitudes and tends to captivate. I try to avoid it when
      I can, though I tolerate it if the day’s treatment requires it. The mid-day light is harsh, austere and
      ruthless. The evening hides more than it illuminates and holds a melancholic mood. It is the late-afternoon
      light that convinces me. The more gentle, thoughtful afternoon light allows an inner illumination, and by
      extension a line of thought, that leaves me in rapture. How do I describe it? It is a softer light, one that
      takes its time and causes the gold of the veldt to age and achieve wisdom before one’s eyes. The various
      sculptures in the courtyard of the Veldt Institute were built specifically—in my opinion, there are those
      who differ—for the afternoon light. The curves and lacunae of the stone work shine with superlative
      brilliance, the wood takes on a radiance. That class of work which supersedes form itself is only truly
      visible in that afternoon light (with the exception of the most subtle class of work which can only be seen in
      the absence of light and the absence of sight itself).
      <br/>
      <br/>
      When I can, I set the afternoons aside for unrestricted contemplation, finding a place in the common area in
      the outer ring, near a south facing window, or in the inner courtyard, where I might sit and watch the cast of
      the light, its movement and consequence of movement as it crosses the field of view. It holds that nostalgia
      for another time, a time in which I have not yet lived. ‘Held’ or ‘generated’? I guess I cannot say, though
      these may be one and the same. I suspect this much is true.
      <br/>
      <br/>
      I only learned to fully appreciate the movement of the light when learning to achieve motionlessness and while
      engaged in the rest cure. What one comes to find early on in their stay at the Veldt Institute—this being one
      of the criteria for moving out of the phase overseen by the first, male, Dr. Mellinger—is that to fully
      appreciate the qualities of the light one must first learn to remain utterly static. We are taught to think of
      movement as residing on an absolute and strictly positive scale, with motionlessness at one terminal end which
      reaches outward toward the limit of light. What one comes to learn under Dr. Mellinger is that there is a realm
      of ‘negative movement’, which exists on the other side of motionlessness. This is a phenomenally difficult
      concept for the new patient to grasp, and you too may find it confounding at first, for the patients lying
      on their chairs all seem to be keeping utterly and equally still. With some practice, and a little guidance
      from Dr. Mellinger, one comes to understand that some patients are in fact <i>more static</i> than others, no
      different from the varying degrees of speed within a group of runners in a heat. As one grows more and more
      adept at motionlessness one finds their inner speed increasing significantly. The more adept one grows at
      remaining static, the better equipped one is to notice the fantastically minor variations of the light as
      it, itself, moves across the field of view.
      <br/>
      <br/>
      It is a joy to witness the patients who have been here the longest, especially those who have dedicated
      themselves particularly to the pursuit of motionlessness. Those who practice assiduously can, in their
      motionlessness, dance and even fly like acrobats.
      </StandardProse>
      <LeftBlackTitle><h3><span className={styles.titleShadow}>myth</span></h3></LeftBlackTitle>
      <StandardProse>
      The advent of the Veldt Institute occurred with the destruction of everything outside of the Veldt
      Institute. This place precipitated on the cool lens of existence from the dust, ash and vapor of the previous
      world. It is important to understand that there is no causal direction to this field of construction and
      destruction: the construction of the Veldt Institute was not caused by the destruction of the world outside, nor
      did the destruction of the world outside cause the construction of the Veldt Institute. Both events occurred
      simultaneously and as a necessary cause and consequence of the other. One could not have become without the
      other and had one not happened the other would not have happened.
      <br/>
      <br/>
      But we patients do not worry about how long the institute has stood, when it was created or why. We work
      under the constructive myth that—as far as any given patient is concerned—the Institute did not exist before
      they arrived and will not exist after they leave. So, to speak ‘truthfully’, the Institute was created when
      I arrived, at the same instant the world outside collapsed. It was born fully formed and the world outside
      fell into dust. Any deeper consideration only serves to distract from one’s time here.
      <br/>
      <br/>
      At the Veldt Institute one comes to learn that it is not the fact that the myths are myths that is
      bothersome, as the world is formed only and entirely of myths within other myths. Rather that it is the myths
      one chooses that is most important. In this way <i>this</i> myth works as well as—or perhaps even a little better
      than—any other myth, at least for the ends set out here. Foremost in importance is that one learns to construct
      their own myths, for this is the only way to take agency over one’s existence.
      </StandardProse>
      <LeftBlackTitle><h3><span className={styles.titleShadow}>trauma</span></h3></LeftBlackTitle>
      <StandardProse>
      Living itself is a form of trauma. A perpetual, nagging trauma that wears one down with its inimical
      persistence. This is considered a truism at the institute.
      <br/>
      <br/>
      To be in the Veldt is to work in a focused way to fight against this trauma and undo it. To fight not only
      against its occurrence in one’s self but its occurrence in all others.
      <br/>
      <br/>
      All of the things we do are done with this intention.
      </StandardProse>
      <LeftBlackTitle><h3><span className={styles.titleShadow}>dreams</span></h3></LeftBlackTitle>
      <StandardProse>
      My dreams. Before coming the Veldt Institute I would never have considered my dreams. They passed through me like
      so much vapor, in and out and forgotten once the day had taken its hold. But now my dreams hamper me. Haunt
      me. They come in reams and waves, crashing in upon me as I sleep, and course through me long after I wake. I must
      struggle with them. I find myself wondering if the contents of these dreams stem from the time before I came to
      the Veldt Institute, if they are premonitions of things to come after I leave, or if they are dreams meant for
      someone else.
      <br/>
      <br/>
      There are no easy answers.
      <br/>
      <br/>
      Dr. Mellinger (the second, the female) has me consider my dreams. This is not some feeble Freudian exercise where
      she casts creative speculation until I am goaded into revealing some long-held resentment. During one of our early
      meetings she said, simply, “From here on out I would like you to consider your dreams deeply.” And I did. It was
      impossible not to. I had resisted them up until that point, worked every morning to reduce their influence on
      myself, until Dr. Mellinger gave me permission to recognize them fully. Until she set me free.
      <br/>
      <br/>
      These were dreams of feelings, of sensations, of abstract emotions. Places I had never been and people I had
      never met, as if I were living other lives. In some of these dreams I was bound in a great mist, something
      golden and formless, like the grass outside the Institute, which flowed around me and had no sticking point.
      <br/>
      <br/>
      The dreams were unsettling until I came to see their rhythm, their many ordered layers of movement. There was
      little I could say about these dreams except that they were, that they bled into my waking life and came to meld
      seamlessly with the edges of my waking consciousness. They have come to me too when I am ordered to sit on one
      of those benches. I have dreams of the sculpture cure where I sit before sculptures that do not exist. These
      dreams come into being with their own agency, setting foot in my life like a spiteful lover whose hand evinces
      fear and admiration at once.
      <br/>
      <br/>
      I am reminded of the angels spoken of in the old testament, the true messengers of god whose presence struck
      the forefathers down with a trembling to their very souls. In the terrible luxury of these dreams I have
      found a sensual foreboding, a sense of my own end that borders on the erotic. But we come to the Veldt
      Institute as renunciants, giving up everything spurious in order to arrive at our full state of being. Are these
      visions not something akin to regression? A menacing?
      <br/>
      <br/>
      Dr. Mellinger has instructed me not to speak of these dreams to any of the other patients. It is easy to think
      that we all have the same dreams, that we all live with the same inner elocution. The hope is that in airing
      these dreams out to one another we will arrive at some common ground, one dream will fill in the gaps of the
      other, and in their commonalities some light will be shed on their meaning. But this could not be further
      from the truth. We are meant to live with these personal signs, to struggle with them in solitude. By relating
      them to one another we would be entering into false hope. We would connect the facile illusions, the surface
      similarities and forget the rest. A forgetting of the understories. The true, ineffable depths washed away. It
      is one of the great struggles of being at the Veldt Institute: seeing these things and hoping to put them
      together, like pieces from different puzzles that just happen—by hope,  chance and misalignment—to have
      complementary angles and which, when combined, might even create an image, but an false image that is nothing
      more than a comforting illusion. These false cognates hinder us further, relegate us to a world of simple
      meaning and cherished places. Clinging to the rock of understanding, to the illusory field of the world as
      it seems, dooming us utterly.
      <br/>
      <br/>
      I’ll tell you my dreams though, as you are a dream yourself. There won’t be any harm in this, airing out
      a dream to a dream deeper still.
      </StandardProse>
      <LeftBlackTitle><h3><span className={styles.titleShadow}>dr. mellinger</span></h3></LeftBlackTitle>
      <StandardProse>
      I came in to Dr. Mellinger’s office today. She is thin and elongated and though she seems very serious she is
      occasionally prone to a dry humor.
      <br/>
      <br/>
      Dr. Mellinger leads a weekly class where she teaches her theory of negative movement through a form of therapeutic
      choreography. Every student at the institute must attend the class once, but continuing on with further classes
      is optional. I attended the first class but have not returned since. There are some patients here whose entire
      course of treatment revolves around this class and Mellinger’s teachings.
      <br/>
      <br/>
      She keeps her door locked and patients must wait outside until she is prepared to see them. I always arrive at
      the appointed time and always must wait before I am let in.
      <br/>
      <br/>
      When I enter the office she does not greet me. Immediately she turns her back to me and sits in her chair. The
      doctors’ offices are all similar in layout but different in detail. Dr. Mellinger’s is spare: two minimalist
      chairs face one another, a floor lamp of very modern design arcs up and around, the golden bulb hovering over
      our heads as in an interrogation room. One large framed work in shades of eggshell and creme hangs on
      the wall; a low, tidy bookshelf; her desk, atop which sits a notebook, some pens and a few paperweights. The
      curve of the narrow, windowed wall faces out into the courtyard.
      <br/>
      <br/>
      Since she asked me to attend to my dreams my time with Dr. Mellinger had been uneventful. Two months
      perhaps. Three times a week I come to her office and we talk about this or that. Nearly all of my time has been
      taken up cleaning the windows, though she has been clear that I am allowed to take as much time for the rest
      cure as I need. In our time together I have felt that she has a distinct disinterest in my case. I cannot
      tell whether this means that my case is hopeless or if it is so banal that it bores her. She asks me unimportant
      questions, “Is your bed satisfactory? Have you been looking at the clouds that have been passing by? What
      shapes do you see in them?”
      <br/>
      <br/>
      She asks me how I like the food.
      <br/>
      <br/>
      But the doctors here use different tactics. They lull you into a sense of complacency. They get you to drop your
      boundaries so that your true feelings show.
      <br/>
      <br/>
      Today I enter and we sit. She always takes a moment to stare at me hard. She may be searching me for some change
      or just working to remember my name. There must be fifteen or twenty other patients under her care at the
      moment, four or five of us coming in every day.
      <br/>
      <br/>
      She looks at her pad, checks something off.
      <br/>
      <br/>
      “Have you considered walking the East Path?”
      <br/>
      <br/>
      I had not even known it was an option. Clearly, the outer path is visible from the Veldt institute itself. Even
      hearing about the other paths there is no clear way to get to them. One might wander out into the Veldt, but
      what would be the point? Far more likely to get lost.
      <br/>
      <br/>
      I tell Dr. Mellinger that I had not considered it.
      <br/>
      <br/>
      “Well? Would you?”
      <br/>
      <br/>
      “Would I like to walk the East Path?” I say.
      <br/>
      <br/>
      “Yes.”
      <br/>
      <br/>
      “If it is indicated in my treatment then, yes. I suppose. Yes.”
      <br/>
      <br/>
      She nods in a perfunctory way then stands and ushers me out of her office. We pass through the outer
      ring of the institute. Some other patients look up at us. There are some faint smiles, some blank stares. I
      barely have time to register these. Then we are outside. The Veldt is the Veldt. We walk clockwise along the
      outer path. With the sun to her face, Dr. Mellinger veers off the outer path and into the Veldt itself. It
      does not slow her for even a moment. She tramps off and I try to keep up. She walks about thirty meters into
      the Veldt then stops. I am just able to catch up when she turns to me.
      <br/>
      <br/>
      “Where is it?”
      <br/>
      <br/>
      “Where is what?”
      <br/>
      <br/>
      “The Eastern path.”
      <br/>
      <br/>
      I shake my head. Shrug.
      <br/>
      <br/>
      She turns to the left and takes off again. Again, I struggle to keep up. She goes for another ten meters then
      stops again.
      <br/>
      <br/>
      “It’s supposed to be right here. Surely—” She trails off, frustrated, holding a hand up to shield her eyes, “Surely
      you know where it is. Go—” She shakes her hand in my direction, “Go look over there. Go find it.”
      <br/>
      <br/>
      “What if I get lost?”
      <br/>
      <br/>
      “You can’t get any more lost than you already are.”
      <br/>
      <br/>
      I retrace my steps then continue on. I turn to see Dr. Mellinger in the near distance, alternately walking in
      circles and scanning the horizon. I go slowly, not knowing what it is I am looking for. The ground is utterly
      homogenous, just the pale grass waving in the wind. I turn toward the Veldt Institute building. It is visible
      still: glowing in the sun about a quarter mile away. This is the furthest I have been from the Institute since
      I first arrived. It is rather beautiful, like it rose up out of the earth or landed from space or just appeared
      one day out of nothingness. A group of swifts or swallows pass by overhead. I am lost in the sparkling of the
      morning light when I hear Mellinger’s footsteps in the grass.
      <br/>
      <br/>
      “Well? Why didn’t you say anything?”
      <br/>
      <br/>
      I come to. “Sorry?”
      <br/>
      <br/>
      She gestures behind me with her open palm, looking stern.
      <br/>
      <br/>
      I turn. Behind me there is a low, flat stone, set at the center of a gravel circle which extends out in one
      direction. The gravel has been recently raked.
      <br/>
      <br/>
      “Take all the time you need,” she says, turning, “Once you return, you will be in the care of Dr.
      Pettibon. Best of luck.”
      </StandardProse>
      <br/>
      <br/>
      <br/>
      <Footer/>
             </body>
         </div>
     )
   }
