import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header.js'
import RightGrayTitle from '../../components/rightGrayTitle.js'
import CenterGrayTitle from '../../components/centerGrayTitle.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Terrarium.module.css'

export default function Terrarium() {
  return (
      <div>
          <Head>
            <title>vi_khi_nao + jess_alexander ~ when_my_body_was_a_glass_terrarium — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="terrariumBackground"/>

       <br/>
       <br/>
       <br/>
       <br/>

       <RightGrayTitle><h3><span
       className={styles.inverseShadow}>w </span><span
       className={styles.titleShadow}>h</span> e <span
       className={styles.inverseShadow}>n</span><br/><span
       className={styles.inverseShadow}>m</span>y <br/><span
       className={styles.titleShadow}>bo </span>dy<br/><br/><span
       className={styles.inverseShadow}>w</span>a<span
       className={styles.inverseShadow}>s</span><br/> a <br/><span
       className={styles.inverseShadow}>g </span>l a <span
       className={styles.titleShadow}>ss</span><br/><br/><span className={styles.titleShadow}> t <span
       className={styles.inverseShadow}>e </span>r</span>r<span
       className={styles.inverseShadow}>a</span><span className={styles.titleShadow}>r </span>i<span
       className={styles.inverseShadow}>u </span>m</h3></RightGrayTitle>

       <br/>

        <br/>

        <CenterGrayTitle>:: vi ::<br/>:: khi nao + jess ::<br/>:: alexander ::</CenterGrayTitle>

        <br/>
        <br/>

<pre className={styles.left}>{`The showerhead at 6AM `}<span
className={styles.alternateVoiceOne}>{` lulls`}</span><br/><span
className={styles.alternateVoiceOne}>{`the  blue room  back to  sleep.`}{`   I  rolled
over  at 6:15  and  watched you wrap  a
towel  around your   head`}</span>{`   and  you
said  good  morning  in   your
rough   and   sultry    morning
voice.  In the breaks between
the   blinds  I   saw  the  night
hang   the   damp   &     dusty
clouds atop a block of square
shaped lofts.`}<br/></pre>

<pre className={styles.left}><span className={styles.alternateVoiceOne}>{`Back  when  I  feared  flying,  I’d  pretend`}</span><br/>
{`airplanes       were          giant
sleighs,  rushing,         rushing
over           the             endless
expanse      of  arctic      snow.`}</pre>

<br/><br/><br/><br/>


<pre className={styles.right}><span
className={styles.alternateVoiceOne}>{`It  took  longer  on   the   drive to    Boulder`}</span>{`
for     the     crisp     outline    of
mountains     to     come     into
focus.            `}<span className={styles.alternateVoiceOne}>Your voice was soft and<br/>distant and </span>{`   you read `}<i>Craft in the<br/>
Real World</i>{` aloud until we grew
bored   of  it.`}<span className={styles.alternateVoiceOne}>You wore </span><span
className={styles.alternateVoiceTwo}>{` a  dark  blue
wrap-around     dress     with      bell
shaped       sleeves    and      flower
print.      `}</span><span className={styles.alternateVoiceOne}>{`You  wore a  special  skin-toned
bra    to    cover    up      the scar bisecting
your      chest.    At    our    apartment,      I
folded you like`}</span>{`the stem of a flower
onto the bed.      `}<span
className={styles.alternateVoiceOne}>{` Your neck smelled
salty &  floral.`}</span><span
className={styles.alternateVoiceTwo}>{`        You rested your left
hand     between    your     shoulder
and right  breast           `}</span><span
className={styles.alternateVoiceOne}>{`&  caught  your
breath.  You   did  this   the  first   night  we
lay together in a bed`}</span>{`    and my  body
turned to   you without moving.`}</pre>


<br/><br/><br/><br/>



                     <Footer/>
                           </body>
                       </div>
                   )
                 }
