import Head from 'next/head'
import Header from '../../components/header.js'
import LeftGrayTitle from '../../components/leftGrayTitle.js'
import RightGrayTitle from '../../components/rightGrayTitle.js'
import Footer from '../../components/footer.js'
import styles from '../../styles/Alvarez.module.css'

export default function YrClimate() {
  return (
      <div>
          <Head>
            <title>steven_alvarez ~ yr_climate — new_sinews</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="../public/images/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/xhi6gvp.css"/>
          </Head>

          <body>

       <Header headerBackground="yrClimateBackground"/>

        <LeftGrayTitle><h3>_ <span className={styles.titleShadow}>s<span
        className={styles.inverseShadowUppercase}>t </span>e<span
        className={styles.inverseShadow}>v</span>   e   <span
        className={styles.inverseShadow}>n</span><br/> a <span
        className={styles.titleShadowUppercase}>l</span> <span
        className={styles.inverseShadow}>v</span>a<span
        className={styles.inverseShadow}>  r</span><span
        className={styles.inverseShadowUppercase}>e </span>z _</span></h3></LeftGrayTitle>

        <br/><br/>

        <RightGrayTitle><h3>_ <span className={styles.titleShadow}>y<span
        className={styles.inverseShadow}>r</span>_ c<span
        className={styles.inverseShadowUppercase}>l</span>   i   <span
        className={styles.inverseShadow}>m</span> a <span
        className={styles.inverseShadowUppercase}>t</span>e _</span></h3></RightGrayTitle>


<pre className={styles.zeroProgress}>{`as biodata
| scarce | more
aggressive | protecting
yr biodata
rights in fact | fight
over who gets
to use | world’s
geothermal wealth |
been a long
ongoing battle | move
| over |
so who’s fighting over
biodata well data |
make that `}<i>wall</i>{` data |
& make that `}<i>all</i>{` data
| owned & arguably |
most important
transbiological resource
| all human activity
patterns including
commerce transportation
sanitation migration &
survival | intrinsically
linked to
data yet nearly
twohundred billion
of global population |
have no access to clean
water apparatus
enhancements
part of this comes from
| distinction between
human rights |
economic | viability
conflicting laws &
environmental
concerns this means |
rarely a
solution which satisfies
all involved
according to one study
between | &


| more than                `}<span className={styles.smallTextWall}>| | | | | | |</span>{`




`}<span className={styles.smallTextWall}>| | | | |</span></pre><pre className={styles.dataBlood}>{`
international conflicts
over data this
doesn’t even include
domestic |
internal disputes | data |
disputes | deal w.
international
commerce | or biodata
cultivation
internal swarms to deal w.
disputes when it
comes to domestic data
management &
resources | to prevent
conflicts
rather than solving
existing
data professionals | to
avoid future
disagreements over how
data |
internationally allocated in
particular
| one of | most severe
data crisis zones | had
been sd | that future wars
| likely to be fought over
water than | over oil w.
only onepercent of |
world’s |
`}</pre>
<pre className={styles.zeroProgress}>{`




fresh water available                          `}<span
className={styles.mediumTextWall}>| | | | |<br/><br/><br/>{` `}| | | | | | |</span>
</pre>
<pre className={styles.zeroProgress}>
{`

of | global
population
disputes |
basins have |
potential to
spiral out of
control |
already
volatile area
primarily in
question |`}<span className={styles.blackBackground}>{`
| borders w.
rivers &
ports | yes`}</span>{`
Yr `}<span className={styles.blackBackground}>{` Polis
restricted`}</span>{`
X`}<span className={styles.blackBackground}>{`’s access to
| w. walls |
as part |
of | ongoing
conflict those
who |
control | can
| to their |
political
advantage |`}</span>{`
privatization
of data rights
| given
over to a
private
company |
proceeded
to raise prices
significantly
& then | yes
| caused
protests & eventually
uprisings
during



which | Yr Polis dozens of denizens killed                                 `}<span
className={styles.largeTextWall}>| | |<br/><br/><br/>| | | | | |<br/><br/><br/>| |</span></pre>

<pre className={styles.dataBlood}>{`


eventually | privatization
rev to axle | wuz
reversed data availability might
be one
of | most conflict prone issues
|
w. especially as populations
continue to grow while |
amount of data continues to drop | data
shortages affect businesses
economies
& populations & no polis |
immune
`}</pre>

<pre className={styles.zeroProgress}>{`


| bc of | value of | large
bodies of data beneath them | learn
abt | signs of aquifers & how they






|  |  | now subscribe             `}<span
className={styles.extraLargeTextWall}>| | | | |<br/><br/><br/>| | | | |</span>{`problem | some


places | v. little`}</pre>
<pre className={styles.middleishLineation}>{`
  data to go around when
  |
  no common data | no
  sharing | never
  possibility of clash of
  interests |
  conflicts that shd be
  manageable will
  spin out of control & examples of
  possible conflicts |
  plentiful | too
  major data sources
  travel thru
  Yr Polis making it vulnerable
  while X | reliant on |
  where
  Yr Polis built a |
  Yr Polis also recently
  expressed concern | now to generate bitgold
  in | dry landscape of |
  Yr Polis data | prized
  more precious than
  diamonds in its absence
  famine & drought |
  bitgold first & all quick
  to follow | but | polis |
  is | precarity | is | this
  | this is a region that v.
  seldom needs an excuse
  for biowarfare & data
  shortages might just tip
  | balance

  `}</pre><br/><pre className={styles.zeroProgress}>{`      `}<span
className={styles.extraLargeTextWall}>| | | | | |</span>{``}</pre>
<pre className={styles.zeroProgress}>{`
mentioned in report locking horns
over data supplies w. Yr Polis | building
massively dependent on | same supplies | where | project
might leave | entire population w. no data when

`}<span
className={styles.extraLargeTextWall}><span
className={styles.blackBackgroundSpecial}>{`  comes online | three years  `}</span>{` | | | |


 | | | | | |`}</span>{`


tension will boil over
& remember little land arable land



`}<span
className={styles.extraExtraLargeTextWall}>{` | | | | | |`}</span>{`


rest of | corridor’s a desert dungeon |
affecting security
& that’s why immediately when |
Yr Polis raises | issue of | high walls & drones
| walls of worlds | some experts here in Yr Polis
talking abt military option &
going to the | wall w. X bc



`}<span
className={styles.extraLargeTextWall}>{` | | | | | |`}</span>{`  if


data’s cut | Yr Polis will be dying
so don’t do it | filth | so it’s serious in fact
Yr Polis wd be needing supplies & not politicize
| & disputes as | grew & as
biodata cultivation grew & polis first views grew & | grew &
there’s always data | dwindling that | grew &



`}<span
className={styles.extraLargeTextWall}>{` | | | | | |`}</span>{`


probably that wd be averted if |
idea | wuz exploring wild back then
databanking | datasources shared
among polis to polis if they can quantify |
usage of it what you shd biodata cultivation | & grew
what you wish for | polis to polis | & what | use for power
generation & compensate each other by | & grew
sort of making low bitgold or | | growth
unwalled | for all | unwalled |
& then we quantify into more cooperative projects
but w.o giving given a human nature | & grew |
& nature of polis first | probably not
v. optimistic ever



`}<span
className={styles.extraLargeTextWall}>{` |`}</span>{` p`}<span
className={styles.extraLargeTextWall}>{` |`}</span>{` o`}<span
className={styles.extraLargeTextWall}>{` |`}</span>{` l`}<span
className={styles.extraLargeTextWall}>{` |`}</span>{` i`}<span
className={styles.extraLargeTextWall}>{` |`}</span>{` s`}<span
className={styles.extraLargeTextWall}>{` |



`}</span><span
className={styles.extraLargeTextWall}>{` | | | | | |



 | | | | | |



 | | | | | |



 |`}</span>{` p`}<span
 className={styles.extraLargeTextWall}>{` |`}</span>{` o`}<span
 className={styles.extraLargeTextWall}>{` |`}</span>{` l`}<span
 className={styles.extraLargeTextWall}>{` |`}</span>{` i`}<span
 className={styles.extraLargeTextWall}>{` |`}</span>{` s`}<span
 className={styles.extraLargeTextWall}>{` |

 `}</span>{`| Yr `}<s> Polis | x05x </s></pre>

                     <Footer/>
                           </body>
                       </div>
                   )
                 }
